Repository Sulagna-Dutta-Roy/GGExtensions, pull requests merged in 2024-07, with the labels that each got.

#2023 Adds minecraft game
  Minecraft/index.html
  Minecraft/manifest.json
  Minecraft/script.js
  Minecraft/styles.css
Labels: gssoc, level2

#2028 Cooking game
  Virtual Cooking /index.html
  Virtual Cooking /manifest.json
  Virtual Cooking /script.js
  Virtual Cooking /style.css
Labels: gssoc, level2

#2030 Bouncing balls
  Bouncing Balls/index.html
  Bouncing Balls/manifest.json
  Bouncing Balls/script.js
  Bouncing Balls/style.css
Labels: gssoc, level2

#2034 Solved #1990- Fractal tree stimulation
  Fractal Tree Stimulation/index5.html
  Fractal Tree Stimulation/manifest.json
  Fractal Tree Stimulation/script5.js
  Fractal Tree Stimulation/styles5.css
Labels: gssoc, level2

#2036 Added Chrome Dino Game
  Chrome Dinosaur Game/README.md
  Chrome Dinosaur Game/assets/big-cactus1.png
  Chrome Dinosaur Game/assets/big-cactus2.png
  Chrome Dinosaur Game/assets/big-cactus3.png
  Chrome Dinosaur Game/assets/bird1.png
  Chrome Dinosaur Game/assets/bird2.png
  Chrome Dinosaur Game/assets/cactus1.png
  Chrome Dinosaur Game/assets/cactus2.png
  Chrome Dinosaur Game/assets/cactus3.png
  Chrome Dinosaur Game/assets/cloud.png
  Chrome Dinosaur Game/assets/dino-dead.png
  Chrome Dinosaur Game/assets/dino-duck1.png
  Chrome Dinosaur Game/assets/dino-duck2.png
  Chrome Dinosaur Game/assets/dino-jump.png
  Chrome Dinosaur Game/assets/dino-run1.png
  Chrome Dinosaur Game/assets/dino-run2.png
  Chrome Dinosaur Game/assets/dino.png
  Chrome Dinosaur Game/assets/game-over.png
  Chrome Dinosaur Game/assets/reset.png
  Chrome Dinosaur Game/assets/sounds/die.mp3
  Chrome Dinosaur Game/assets/sounds/jump.mp3
  Chrome Dinosaur Game/assets/sounds/point.mp3
  Chrome Dinosaur Game/assets/track.png
  Chrome Dinosaur Game/index.html
  Chrome Dinosaur Game/manifest.json
  Chrome Dinosaur Game/script.js
  Chrome Dinosaur Game/style.css
Labels: gssoc, level2

#2044 Added Ludo Game
  Ludo/assets/images/background.jpg
  Ludo/assets/images/crown1.png
  Ludo/assets/images/crown2.png
  Ludo/assets/images/crown3.png
  Ludo/assets/images/dice_1.png
  Ludo/assets/images/im
  Ludo/assets/images/logo.png
  Ludo/assets/sounds/dice.mp3
  Ludo/assets/sounds/inout.mp3
  Ludo/assets/sounds/killed.mp3
  Ludo/assets/sounds/s
  Ludo/assets/sounds/step.mp3
  Ludo/assets/sounds/win.mp3
  Ludo/index.html
  Ludo/manifest.json
  Ludo/script.js
  Ludo/style.css
Labels: gssoc, level2

#2045 Solved #2021- Hex FRVR Game
  Hex FRVR Game/index.html
  Hex FRVR Game/mannifest.json
  Hex FRVR Game/script.js
  Hex FRVR Game/styles.css
Labels: gssoc, level2

#2046 Added HTML5 Gamepad controller tester
  HTML5 Gamepad  Tester/Readme.md
  HTML5 Gamepad  Tester/index.html
  HTML5 Gamepad  Tester/manifest.json
  HTML5 Gamepad  Tester/script.js
  HTML5 Gamepad  Tester/style.css
Labels: gssoc, level2

#2051 Add picross game #1489
  Picross/README.md
  Picross/css/picross.css
  Picross/css/reset.css
  Picross/images/rainbow.gif
  Picross/index.html
  Picross/js/backbone.js
  Picross/js/jquery-1.8.3.js
  Picross/js/picross.js
  Picross/js/seedrandom.js
  Picross/js/underscore.js
Labels: gssoc, level2

#2055 Now the text such as Basic mode and scientific mode is not displayed on the result.
  Calculator/scripts/script.js
Labels: gssoc, level1

#2056 Added Asteroids game extension
  Asteroids/icon.png
  Asteroids/index.html
  Asteroids/manifest.json
  Asteroids/script.js
  Asteroids/style.css
Labels: gssoc, level2

#2062 Added Hand Cricket
  Hand Cricket/Images/five.png
  Hand Cricket/Images/four.png
  Hand Cricket/Images/one.png
  Hand Cricket/Images/six.png
  Hand Cricket/Images/three.png
  Hand Cricket/Images/two.png
  Hand Cricket/Readme.md
  Hand Cricket/index.html
  Hand Cricket/manifest.json
  Hand Cricket/script.js
  Hand Cricket/style.css
Labels: gssoc, level2

#2071 Bug fix: Chess game chrome extension not loading
  Chess Game/css/styles.css
  Chess Game/index.html
  Chess Game/js/jquery.js
  Chess Game/manifest.json
Labels: gssoc, level1

#2072 Solved #2022- hexsweep game
  Hexsweep Game/index.html
  Hexsweep Game/manifest.json
  Hexsweep Game/script.js
  Hexsweep Game/styles.css
Labels: gssoc, level2

#2073 Added Guitar
  Guitar/README.md
  Guitar/index.html
  Guitar/manifest.json
  Guitar/script.js
  Guitar/style.css
Labels: gssoc, level1

#2074 Added Digital Dilemma
  Digital Dilemma/index.html
  Digital Dilemma/manifest.json
  Digital Dilemma/script.js
  Digital Dilemma/styles.scss
Labels: gssoc, level2

#2049 Added scroll dark run game
  Dark Run Game/Grass.png
  Dark Run Game/bg-forest.jpg
  Dark Run Game/bird.png
  Dark Run Game/bush-monster.png
  Dark Run Game/bush.png
  Dark Run Game/go-right.png
  Dark Run Game/house.png
  Dark Run Game/idle-back.png
  Dark Run Game/idle.png
  Dark Run Game/index.html
  Dark Run Game/main.js
  Dark Run Game/manifest.json
  Dark Run Game/pillar.png
  Dark Run Game/running-back.png
  Dark Run Game/running.png
  Dark Run Game/saw.png
  Dark Run Game/style.css
  Dark Run Game/trees-01.png
  Dark Run Game/trees-02.png
  Dark Run Game/trees-03.png
  Dark Run Game/trees-1.png
Labels: gssoc, level2

#2069 ADDED MOTO CROSS GAME
  Moto Cross Game/README.md
  Moto Cross Game/index.html
  Moto Cross Game/manifest.json
  Moto Cross Game/script.js
  Moto Cross Game/style.css
Labels: gssoc, level2

#2076 Adds game Angry Birds
  Angry Bird/index.html
  Angry Bird/manifest.json
  Angry Bird/script.js
  Angry Bird/styles.css
Labels: gssoc, level2

#2079 Improved UI of Fidget Spinner Game
  Fidget spinner Game/popup.html
  Fidget spinner Game/style.css
Labels: gssoc, level1

#2083 block by block added
  Block by Block/icon.png
  Block by Block/index.html
  Block by Block/manifest.json
  Block by Block/script.js
  Block by Block/style.css
Labels: gssoc, level2

#2088 2D Breakout Game Added
  2D Breakout Game/index.html
  2D Breakout Game/manifest.json
  2D Breakout Game/script.js
  2D Breakout Game/styles.css
Labels: gssoc, level2

#2085 computer Bingo #2053
  Computer Bingo/favicon/image.png
  Computer Bingo/image.png
  Computer Bingo/index.html
  Computer Bingo/manifest.json
  Computer Bingo/script.js
  Computer Bingo/style.css
  Crack code/index.html
  Crack code/script.js
  Crack code/style.css
Labels: gssoc, level2

#2098 Added Catch Ralph
  Catch Ralph/audios/hit.m4a
  Catch Ralph/images/favicon.jpg
  Catch Ralph/images/player.png
  Catch Ralph/images/ralph.png
  Catch Ralph/images/wall.png
  Catch Ralph/index.html
  Catch Ralph/manifest.json
  Catch Ralph/scripts/engine.js
  Catch Ralph/styles/main.css
  Catch Ralph/styles/reset.css
Labels: gssoc, level2

#2099 Adds "Clash Of Clans" game
  Clash Of Clans/index.html
  Clash Of Clans/manifest.json
  Clash Of Clans/script.js
  Clash Of Clans/styles.css
Labels: gssoc, level2

#2107 Added Mario Game
  Mario Jump/bg.png
  Mario Jump/dino.png
  Mario Jump/dragon.png
  Mario Jump/gameover.mp3
  Mario Jump/index.html
  Mario Jump/manifest.json
  Mario Jump/mario.png
  Mario Jump/music.mp3
  Mario Jump/script.js
  Mario Jump/style.css
Labels: gssoc, level2

#2110 Solved #2089- Slay the spire
  Slay the Spire/index.html
  Slay the Spire/manifest.json
  Slay the Spire/script.js
  Slay the Spire/styles.css
Labels: gssoc, level2

#2117 Added Leap Year Calculator Extension: #766
  Leap Year Calulator Extension/manifest.json
  Leap Year Calulator Extension/popup.html
  Leap Year Calulator Extension/script.js
  Leap Year Calulator Extension/style.css
Labels: gssoc, level1

#2118 Bug Fix: CGPI Calc & AtoZ learning extension errors
  A-Z English Learning/manifest.json
  A-Z English Learning/popup.css
  A-Z English Learning/popup.html
  A-Z English Learning/popup.js
  Complex CGPA Calculator/src/style.css
Labels: gssoc, level1

#2125 Proper action takes on click of buttons in Figma Extension.
  Figma/popup.html
  Figma/styles.css
  Figma/welcome.html
Labels: gssoc, level1

#2135 Added Clock Hands Angle Calculator Extension: #1188
  Clock Hands Angle Calculator Extension/manifest.json
  Clock Hands Angle Calculator Extension/popup.html
  Clock Hands Angle Calculator Extension/script.js
  Clock Hands Angle Calculator Extension/style.css
Labels: gssoc, level1

#2133 Solved #2091- Battle for Wesnoth
  Battle for Wesnoth/index.html
  Battle for Wesnoth/manifest.json
  Battle for Wesnoth/script.js
  Battle for Wesnoth/styles.css
Labels: gssoc, level2

#2112 Improved UI of Random Bible Verse Extension
  Random Bible verse/popup.html
  Random Bible verse/styles.css
Labels: gssoc, level1

#2140 Adding Volume Calculator
  Volume Calculator/manifest.json
  Volume Calculator/popup.css
  Volume Calculator/popup.html
  Volume Calculator/popup.js
Labels: gssoc, level1

#2143 Bug Eliminator game extension added
  Bug Eliminator/app.html
  Bug Eliminator/estilo.css
  Bug Eliminator/fim_de_jogo.html
  Bug Eliminator/icon.png
  Bug Eliminator/img/bg.jpg
  Bug Eliminator/img/coracao_cheio.png
  Bug Eliminator/img/coracao_vazio.png
  Bug Eliminator/img/game_over.png
  Bug Eliminator/img/mata_mosquito.png
  Bug Eliminator/img/mosca.png
  Bug Eliminator/index.html
  Bug Eliminator/jogo.js
  Bug Eliminator/manifest.json
  Bug Eliminator/vitoria.html
Labels: gssoc, level2

#2145 Added Star Rating Component
  Star Rating Component/images/icon-star.svg
  Star Rating Component/images/illustration-thank-you.svg
  Star Rating Component/index.html
  Star Rating Component/manifest.json
  Star Rating Component/script.js
  Star Rating Component/style.css
Labels: gssoc, level2

#2146 Added Temple Run Game
  Temple Run/index.html
  Temple Run/manifest.json
  Temple Run/script.js
  Temple Run/styles.css
Labels: gssoc, level2

#2148 Pet age calculator Extension added
  Pet Age Calculator/manifest.json
  Pet Age Calculator/popup.html
  Pet Age Calculator/script.js
  Pet Age Calculator/style.css
Labels: gssoc, level2

#2150 Added Name Fate
  Crack code/your files/index.html
  Crack code/your files/manifest.json
  Crack code/your files/script.js
  Crack code/your files/style.css
  Name Fate/index.html
  Name Fate/manifest.json
  Name Fate/script.js
  Name Fate/styles.css
Labels: gssoc, level2

#2151 Solved #2090- Hoplite
  Hoplite/index.html
  Hoplite/manifest.json
  Hoplite/script.js
  Hoplite/styles.css
Labels: gssoc, level2

#2155 Added Flames Calculator
  Flames Calculator/Styles.css
  Flames Calculator/index.html
  Flames Calculator/manifest.json
  Flames Calculator/script.js
Labels: gssoc, level1

#2156 Bullseye Game Added
  Bullseye Game/index.html
  Bullseye Game/manifest.json
  Bullseye Game/script.js
  Bullseye Game/style.css
Labels: gssoc, level2

#2157 Added Fruit Matcher
  Fruit Matcher/index.html
  Fruit Matcher/manifest.json
  Fruit Matcher/script.js
  Fruit Matcher/style.css
Labels: gssoc, level2

#2158 Added Corona Shooter
  Corona Shooter/index.html
  Corona Shooter/manifest.json
  Corona Shooter/script.js
  Corona Shooter/styles.css
Labels: gssoc, level2

#2162 Added Midpoint Calculator Extension: #2153
  Midpoint Calculator Extension/manifest.json
  Midpoint Calculator Extension/popup.html
  Midpoint Calculator Extension/script.js
  Midpoint Calculator Extension/style.css
Labels: gssoc, level1

#2164 Added the Projectile Motion Game #2129
  Projectile Motion Game/celebrate.html
  Projectile Motion Game/dot.png
  Projectile Motion Game/fail.html
  Projectile Motion Game/index.html
  Projectile Motion Game/manifest.json
  Projectile Motion Game/play.html
Labels: gssoc, level2

#2170 Zurbo Game
  Zurbo Game/index.html
  Zurbo Game/manifest.json
Labels: gssoc, level2

#2181 added an extension dodge the ball
  Dodge the Ball/manifest.json
  Dodge the Ball/popup.css
  Dodge the Ball/popup.html
  Dodge the Ball/popup.js
Labels: gssoc, level1

#2173 Spider man go Added
  Spider Man Go/audio/60-theme-song.mp3
  Spider Man Go/audio/amazing-spider-man-2.mp3
  Spider Man Go/audio/animated-series-theme.mp3
  Spider Man Go/audio/old-theme.mp3
  Spider Man Go/audio/shooting-web.mp3
  Spider Man Go/css/spiderman-game.css
  Spider Man Go/fonts/Adventure.ttf
  Spider Man Go/fonts/pixel.otf
  Spider Man Go/index.html
  Spider Man Go/manifest.json
  Spider Man Go/spiderman-game.js
  Spider Man Go/styles.css
Labels: gssoc, level2

#2192 Added Carrom Game
  Carrom Game/carrom.html
  Carrom Game/carrom.jpg
  Carrom Game/css/bootstrap.min.css
  Carrom Game/css/main.css
  Carrom Game/js/bootstrap.min.js
  Carrom Game/js/canvasCalls.js
  Carrom Game/js/canvasFunc.js
  Carrom Game/js/coinFunc.js
  Carrom Game/js/jquery.js
  Carrom Game/js/main.js
  Carrom Game/manifest.json
Labels: gssoc, level2

#2168 Added Python cheat sheet
  Python Cheat Sheet/manifest.json
  Python Cheat Sheet/python.md
Labels: gssoc, level1

#2197 Fly Fighter Game
  Fly Fighter Game/README.md
  Fly Fighter Game/assets/back.jpg
  Fly Fighter Game/assets/laser.mp3
  Fly Fighter Game/assets/main.js
  Fly Fighter Game/assets/main2.js
  Fly Fighter Game/assets/musuh.png
  Fly Fighter Game/assets/reload.mp3
  Fly Fighter Game/assets/ship.png
  Fly Fighter Game/assets/style.css
  Fly Fighter Game/index.html
  Fly Fighter Game/manifest.json
  Fly Fighter Game/modul/laser.m4a
  Fly Fighter Game/modul/reload.amr
Labels: gssoc, level2

#2198 Square Root Calculator is added
  Square Root/index.html
  Square Root/manifest.json
  Square Root/script.js
  Square Root/style.css
Labels: gssoc, level1

#2204 Added an extension Web Capture
  Web Capture/background.js
  Web Capture/extractText.js
  Web Capture/manifest.json
  Web Capture/popup.html
  Web Capture/popup.js
Labels: gssoc, level2

#2205 Vowel Consonant Counter is added
  Vowel Consonant Counter/index.html
  Vowel Consonant Counter/manifest.json
  Vowel Consonant Counter/script.js
  Vowel Consonant Counter/style.css
Labels: gssoc, level1

#2206 Modified UI of EyeCare Extension.
  EyeCare/options.html
  EyeCare/popup.html
  EyeCare/styles.css
Labels: gssoc, level2

#2209 Added Cable Maze
  Cable Maze/index.html
  Cable Maze/main.js
  Cable Maze/manifest.json
Labels: gssoc, level2

#2210 Added Back To Top Extension
  Back To Top/index.html
  Back To Top/manifest.json
  Back To Top/script.js
  Back To Top/styles.css
Labels: gssoc, level1

#2211 Added game Traffic Run
  Traffic Run/assests/images/Traffic_Run.PNG
  Traffic Run/index.html
  Traffic Run/manifest.json
  Traffic Run/script.js
  Traffic Run/style.css
Labels: gssoc, level2

#2212 Fibonacci number calculator is added
  Fibonacci Number/index.html
  Fibonacci Number/manifest.json
  Fibonacci Number/script.js
  Fibonacci Number/style.css
Labels: gssoc, level2

#2219 added an extension for a game shape matcher
  Shape Matcher/manifest.json
  Shape Matcher/popup.css
  Shape Matcher/popup.html
  Shape Matcher/popup.js
Labels: gssoc, level2

#2220 Card game extension added
  Card Game/images/AceSpades.png
  Card Game/images/card-AceSpades.png
  Card Game/images/card-JackClubs.png
  Card Game/images/card-KingHearts.png
  Card Game/images/card-QueenDiamonds.png
  Card Game/images/card-back-Blue.png
  Card Game/index.html
  Card Game/index.js
  Card Game/manifest.json
  Card Game/style.css
Labels: gssoc, level1

#2221 added emoji game
  World On Emoji/README.md
  World On Emoji/background.jpeg
  World On Emoji/index.html
  World On Emoji/manifest.json
  World On Emoji/script.js
  World On Emoji/styles.css
Labels: gssoc, level2

#2231 Volumes of 3D Shapes Calculator is added
  Volume of 3D Shapes/index.html
  Volume of 3D Shapes/manifest.json
  Volume of 3D Shapes/script.js
  Volume of 3D Shapes/style.css
Labels: gssoc, level1

#2234 Added Mean, Median and Mode Calculator Extension: #2223
  Mean, Median and Mode Calculator Extension/manifest.json
  Mean, Median and Mode Calculator Extension/popup.html
  Mean, Median and Mode Calculator Extension/script.js
  Mean, Median and Mode Calculator Extension/style.css
Labels: gssoc, level2

#2237 Complex Number Calculator is added
  Complex Number Calculator/index.html
  Complex Number Calculator/manifest.json
  Complex Number Calculator/script.js
  Complex Number Calculator/style.css
  Vowel Counter/background.js
  Vowel Counter/bg.avif
  Vowel Counter/manifest.json
  Vowel Counter/popup.css
  Vowel Counter/popup.html
  Vowel Counter/popup.js
Labels: gssoc, level1

#2239 Cosine Formula is added
  Cosine Formula/index.html
  Cosine Formula/manifest.json
  Cosine Formula/script.js
  Cosine Formula/style.css
Labels: gssoc, level1

#2245 City Bulider Game is added
  Ball Shooting Game/index.html
  Ball Shooting Game/script.js
  Ball Shooting Game/styles.css
  City Bulider Game/README.md
  City Bulider Game/index.html
  City Bulider Game/script.js
  City Bulider Game/styles.css
Labels: gssoc, level2

#2242 Ball Shooting Game is added
  Ball Shooting Game/index.html
  Ball Shooting Game/script.js
  Ball Shooting Game/styles.css
Labels: gssoc, level2

#2246 added an extension for memory flip game
  Memory Flip/manifest.json
  Memory Flip/popup.css
  Memory Flip/popup.html
  Memory Flip/popup.js
Labels: gssoc, level2

#2251 Boyle Temperature Calculator is added
  Boyle Temperature Calculator/index.html
  Boyle Temperature Calculator/manifest.json
  Boyle Temperature Calculator/script.js
  Boyle Temperature Calculator/style.css
Labels: gssoc, level2

#2254 Added Article Summarizer
  Article Summarizer/background.js
  Article Summarizer/content.js
  Article Summarizer/manifest.json
  Article Summarizer/popup.html
  Article Summarizer/popup.js
Labels: gssoc, level2

#2238 Added Html cheat sheet
  Html Cheat Sheet/cheatsheet1.png
  Html Cheat Sheet/cheatsheet2.png
  Html Cheat Sheet/htmlcheatsheet.md
  Html Cheat Sheet/manifest.json
Labels: gssoc, level1

#2256 Cube Root Calculator is added
  Cube Root Calculator/index.html
  Cube Root Calculator/manifest.json
  Cube Root Calculator/script.js
  Cube Root Calculator/style.css
Labels: gssoc, level2

#2257 Added Website Scraper
  Website Scraper/background.js
  Website Scraper/icon128.png
  Website Scraper/icon16.png
  Website Scraper/icon48.png
  Website Scraper/index.html
  Website Scraper/manifest.json
  Website Scraper/script.js
  Website Scraper/style.css
Labels: gssoc, level2

#2260 Cricket Calculator is added
  Cricket Calculator/index.html
  Cricket Calculator/manifest.json
  Cricket Calculator/script.js
  Cricket Calculator/style.css
Labels: gssoc, level2

#2262 Alien Invansion Added
  Alien Invansion/assets/0.png
  Alien Invansion/assets/1.png
  Alien Invansion/assets/2.png
  Alien Invansion/assets/3.png
  Alien Invansion/assets/images/Screenshot 2023-10-02 000328.png
  Alien Invansion/assets/shooter.png
  Alien Invansion/index.html
  Alien Invansion/manifest.json
  Alien Invansion/script.js
  Alien Invansion/style.css
Labels: gssoc, level2

#2268 Added Word Sprint Game
  Word Sprint/README.md
  Word Sprint/game.png
  Word Sprint/home.png
  Word Sprint/index.html
  Word Sprint/manifest.json
  Word Sprint/script.js
  Word Sprint/style.css
Labels: gssoc, level2

#2270 Bug Fix: BasketBall & Block by Block extension
  Basketball Game/css/main.css
  Basketball Game/gsap.js
  Basketball Game/index.html
  Basketball Game/main.js
  Basketball Game/manifest.json
  Block by Block/index.html
  Block by Block/manifest.json
  Block by Block/script.js
  Block by Block/style.css
Labels: bug, gssoc, level2

#2271 Added Chopsticks
  Chopsticks/index.html
  Chopsticks/manifest.json
  Chopsticks/media/Down.png
  Chopsticks/media/Up.png
  Chopsticks/media/blog.png
  Chopsticks/media/cup.jpg
  Chopsticks/media/play-button.png
  Chopsticks/media/points-0-selected.svg
  Chopsticks/media/points-0-unselected.svg
  Chopsticks/media/points-1-selected.svg
  Chopsticks/media/points-1-unselected.svg
  Chopsticks/media/points-2-selected.svg
  Chopsticks/media/points-2-unselected.svg
  Chopsticks/media/points-3-selected.svg
  Chopsticks/media/points-3-unselected.svg
  Chopsticks/media/points-4-selected.svg
  Chopsticks/media/points-4-unselected.svg
  Chopsticks/media/update.png
  Chopsticks/script.js
  Chopsticks/style.css
Labels: gssoc, level2

#2295 Death By Hamster Game Extension Added
  Death By Hamster/README.md
  Death By Hamster/aimerthing.png
  Death By Hamster/arw.png
  Death By Hamster/blip.mp3
  Death By Hamster/cursor.png
  Death By Hamster/favicon.ico
  Death By Hamster/game.js
  Death By Hamster/gun.png
  Death By Hamster/hamster.png
  Death By Hamster/human.png
  Death By Hamster/index.html
  Death By Hamster/letters.js
  Death By Hamster/logothing.png
  Death By Hamster/lzs.js
  Death By Hamster/minify.py
  Death By Hamster/t.png
Labels: gssoc, level2

#2298 Frequency Calculator is added
  Frequency Calcullator/index.html
  Frequency Calcullator/manifest.json
  Frequency Calcullator/script.js
  Frequency Calcullator/style.css
Labels: gssoc, level1

#2300 Bug Fix: Connect Four & BackToTop extension errors Fix
  Back To Top/index.html
  Back To Top/manifest.json
  Back To Top/script.js
  Back To Top/styles.css
  Connect Four Game Extension/manifest.json
  Connect Four Game Extension/scripts/script.js
Labels: gssoc, level2

#2301 Virtual Study Group
  Virtual Study Group/README.md
  Virtual Study Group/background.js
  Virtual Study Group/manifest.json
  Virtual Study Group/popup.css
  Virtual Study Group/popup.html
  Virtual Study Group/popup.js
Labels: gssoc, level1

#2302 Added email manager
  Email Manager/background.js
  Email Manager/content.js
  Email Manager/manifest.json
  Email Manager/popup.html
  Email Manager/popup.js
Labels: gssoc, level1

#2311 Youtube to mp3/mp4
  Youtube to MP3 or Mp4/README.md
  Youtube to MP3 or Mp4/html and css/popup.html
  Youtube to MP3 or Mp4/html and css/styles.css
  Youtube to MP3 or Mp4/img/logo64.png
  Youtube to MP3 or Mp4/img/logo96.png
  Youtube to MP3 or Mp4/manifest.json
  Youtube to MP3 or Mp4/scripts/contentScript.js
  Youtube to MP3 or Mp4/scripts/script.js
Labels: gssoc, level2

#2312 General Root Determine Calculator is added
  General Root Determine Calculator/index.html
  General Root Determine Calculator/manifest.json
  General Root Determine Calculator/script.js
  General Root Determine Calculator/style.css
Labels: gssoc, level1

#2313 Space Craft Game
  Space Craft Game/background.gif
  Space Craft Game/end.gif
  Space Craft Game/manifest.json
  Space Craft Game/player.gif
  Space Craft Game/space_station.py
Labels: gssoc, level1

#2314 Added BookMark Quest - an RPG game
  Bookmark Quest Game/background.js
  Bookmark Quest Game/content.js
  Bookmark Quest Game/manifest.json
  Bookmark Quest Game/popup.html
  Bookmark Quest Game/popup.js
Labels: gssoc, level2

#2318 added general knowlege quiz extension
  General Knowlege Quiz/README.md
  General Knowlege Quiz/icon.png
  General Knowlege Quiz/index.html
  General Knowlege Quiz/manifest.json
  General Knowlege Quiz/script.js
  General Knowlege Quiz/style.css
Labels: gssoc, level2

#2319 Cricket quiz extension
  Cricket Quiz/icon.png
  Cricket Quiz/index.html
  Cricket Quiz/manifest.json
  Cricket Quiz/script.js
  Cricket Quiz/style.css
Labels: gssoc, level1

#2320 Added 3D Distance Calculator files
  3D distance calculator/manifest.json
  3D distance calculator/popup.html
  3D distance calculator/script.js
  3D distance calculator/style.css
Labels: gssoc, level1

#2322 Solved #2287- Hexquest game extension
  Hexquest game/index.html
  Hexquest game/manifest.json
  Hexquest game/script.js
  Hexquest game/styles.css
Labels: gssoc, level2

#2323 Reversi
  Reversi/README.md
  Reversi/manifest.json
  Reversi/popup.html
  Reversi/script.js
  Reversi/styles.css
Labels: gssoc, level2

#2329 Add Bow and Arrow
  Bow and Arrow/README.md
  Bow and Arrow/index.html
  Bow and Arrow/manifest.json
  Bow and Arrow/script.js
  Bow and Arrow/styles.css
Labels: gssoc, level2

#2330 add snake water gun game
  README.md
  Snake Water Gun/composer.json
  Snake Water Gun/index.html
  Snake Water Gun/index.php
  Snake Water Gun/static/css/swg.css
  Snake Water Gun/static/images/cong1.jpg
  Snake Water Gun/static/images/copy.png
  Snake Water Gun/static/images/draw.jpg
  Snake Water Gun/static/images/email.png
  Snake Water Gun/static/images/facebook.png
  Snake Water Gun/static/images/gun.jpg
  Snake Water Gun/static/images/instagram.jpg
  Snake Water Gun/static/images/linkedin.jpg
  Snake Water Gun/static/images/snake.jpg
  Snake Water Gun/static/images/water.jpg
  Snake Water Gun/static/images/whatsapp.jpg
  Snake Water Gun/static/js/swg.js
Labels: gssoc, level2

#2331 Added Magic 8 Ball
  Magic Eight Ball/index.html
  Magic Eight Ball/manifest.json
  Magic Eight Ball/script.js
  Magic Eight Ball/style.css
Labels: gssoc, level2

#2339 Want to add my PRS entry in README.md
  README.md
Labels: gssoc, level1

#2317 Added Falling Skies Games
  Falling Skies Game/background.gif
  Falling Skies Game/deer_left.gif
  Falling Skies Game/deer_right.gif
  Falling Skies Game/falling_skies.py
  Falling Skies Game/hunter.gif
  Falling Skies Game/manifest.json
  Falling Skies Game/nut.gif
Labels: gssoc, level2

#2337 Added Hill Climb Racing Game!
  Hill Climb Racing Game/Car.js
  Hill Climb Racing Game/ConnectionGene.js
  Hill Climb Racing Game/ConnectionHistory.js
  Hill Climb Racing Game/GENOME.JS
  Hill Climb Racing Game/Ground.js
  Hill Climb Racing Game/Neat.js
  Hill Climb Racing Game/Node.js
  Hill Climb Racing Game/Person.js
  Hill Climb Racing Game/Pics/CBHead2.png
  Hill Climb Racing Game/Pics/CBHead3.png
  Hill Climb Racing Game/Pics/car.png
  Hill Climb Racing Game/Pics/darkness.png
  Hill Climb Racing Game/Pics/grass.png
  Hill Climb Racing Game/Pics/grass2.png
  Hill Climb Racing Game/Pics/grass3.png
  Hill Climb Racing Game/Pics/grass4.png
  Hill Climb Racing Game/Pics/grass5.png
  Hill Climb Racing Game/Pics/grass6.png
  Hill Climb Racing Game/Pics/head.png
  Hill Climb Racing Game/Pics/headLarge.png
  Hill Climb Racing Game/Pics/sky.png
  Hill Climb Racing Game/Pics/wheel.png
  Hill Climb Racing Game/Pics/wheel2.png
  Hill Climb Racing Game/Player.js
  Hill Climb Racing Game/PlayerOld.js
  Hill Climb Racing Game/Population.js
  Hill Climb Racing Game/README.md
  Hill Climb Racing Game/Species.js
  Hill Climb Racing Game/Wheel.js
  Hill Climb Racing Game/World.js
  Hill Climb Racing Game/index.html
  Hill Climb Racing Game/libraries/Box2d.js
  Hill Climb Racing Game/libraries/p5.dom.js
  Hill Climb Racing Game/libraries/p5.js
  Hill Climb Racing Game/libraries/p5.sound.js
  Hill Climb Racing Game/manifest.json
  Hill Climb Racing Game/sketch.js
Labels: gssoc, level2

#2350 added an extension for quick math quiz
  Quick Math Quiz/manifest.json
  Quick Math Quiz/popup.css
  Quick Math Quiz/popup.html
  Quick Math Quiz/popup.js
Labels: gssoc, level2

#2352 3D Maze
  3D Maze/README.md
  3D Maze/index.html
  3D Maze/manifest.json
  3D Maze/script.js
  3D Maze/style.css
Labels: gssoc, level2

#2353 Feat : Rabbit chase game
  .vscode/settings.json
  README.md
  Rabbit Chase Game/README.md
  Rabbit Chase Game/index.html
  Rabbit Chase Game/manifest.json
  Rabbit Chase Game/rabbit.png
  Rabbit Chase Game/script.js
  Rabbit Chase Game/style.css
Labels: gssoc, level2

#2355 Gravity Simulation Game
  Gravity Simulation Game/index.html
  Gravity Simulation Game/manifest.json
  Gravity Simulation Game/script.js
  Gravity Simulation Game/style.css
Labels: gssoc, level1

#2358 Solved #2338- Hexpuzzle game
  Hexpuzzle/index.html
  Hexpuzzle/manifest.json
  Hexpuzzle/script.js
  Hexpuzzle/styles.css
Labels: gssoc, level2

#2360 Added Solitaire Game
  Solitaire/README.md
  Solitaire/cards.js
  Solitaire/game.png
  Solitaire/index.html
  Solitaire/manifest.json
  Solitaire/script.js
  Solitaire/src/bg.jpg
  Solitaire/src/spritesheet.png
  Solitaire/style.css
Labels: gssoc, level2

#2361 Bug Fix: Break the Block extension errors
  Break The Block/manifest.json
  Break The Block/style.css
Labels: gssoc, level1

#2365 Chemistry Quiz Extension
  Chemistry Quiz/icon.png
  Chemistry Quiz/index.html
  Chemistry Quiz/manifest.json
  Chemistry Quiz/script.js
  Chemistry Quiz/style.css
Labels: gssoc, level1

#2367 Add NInja Hattori Game
  Ninja Hattori Game/README.md
  Ninja Hattori Game/hattory.png
  Ninja Hattori Game/index.html
  Ninja Hattori Game/kiyo.png
  Ninja Hattori Game/manifest.json
  Ninja Hattori Game/nhome.jpg
  Ninja Hattori Game/ninja.mp3
  Ninja Hattori Game/script.js
  Ninja Hattori Game/style.css
  README.md
Labels: gssoc, level2

#2372 ADDED TRUCK GAME
  Truck Game/README.md
  Truck Game/css/main.css
  Truck Game/index.html
  Truck Game/js/ball.js
  Truck Game/js/logger.js
  Truck Game/js/main.js
  Truck Game/js/truck.js
  Truck Game/manifest.json
Labels: gssoc, level1

#2375 ADDED HUNGRY SHARK GAME
  Hungry Shark Game/README.md
  Hungry Shark Game/lib/use-game-reducer.ts
  Hungry Shark Game/lib/use-interval.js
  Hungry Shark Game/manifest.json
  Hungry Shark Game/next-env.d.ts
  Hungry Shark Game/package.json
  Hungry Shark Game/pages/index.tsx
  Hungry Shark Game/public/android-chrome-144x144.png
  Hungry Shark Game/public/apple-touch-icon.png
  Hungry Shark Game/public/browserconfig.xml
  Hungry Shark Game/public/emoji/blowfish.png
  Hungry Shark Game/public/emoji/crab.png
  Hungry Shark Game/public/emoji/dolphin.png
  Hungry Shark Game/public/emoji/down.png
  Hungry Shark Game/public/emoji/fish.png
  Hungry Shark Game/public/emoji/left.png
  Hungry Shark Game/public/emoji/lobster.png
  Hungry Shark Game/public/emoji/octopus.png
  Hungry Shark Game/public/emoji/pause.png
  Hungry Shark Game/public/emoji/play-pause.png
  Hungry Shark Game/public/emoji/restart.png
  Hungry Shark Game/public/emoji/right.png
  Hungry Shark Game/public/emoji/settings.png
  Hungry Shark Game/public/emoji/shark.png
  Hungry Shark Game/public/emoji/shrimp.png
  Hungry Shark Game/public/emoji/spiral-shell.png
  Hungry Shark Game/public/emoji/spouting-whale.png
  Hungry Shark Game/public/emoji/squid.png
  Hungry Shark Game/public/emoji/trophy.png
  Hungry Shark Game/public/emoji/tropical-fish.png
  Hungry Shark Game/public/emoji/up.png
  Hungry Shark Game/public/emoji/whale.png
  Hungry Shark Game/public/favicon-16x16.png
  Hungry Shark Game/public/favicon-32x32.png
  Hungry Shark Game/public/favicon.ico
  Hungry Shark Game/public/mstile-150x150.png
  Hungry Shark Game/public/reef-bg.jpg
  Hungry Shark Game/public/robots.txt
  Hungry Shark Game/public/safari-pinned-tab.svg
  Hungry Shark Game/public/site.webmanifest
  Hungry Shark Game/tsconfig.json
  Hungry Shark Game/yarn-error.log
  Hungry Shark Game/yarn.lock
Labels: gssoc, level1

#2384 Baseball Game is added
  Baseball Game/README.md
  Baseball Game/assets/batter.jpeg
  Baseball Game/assets/pitcher.jpeg
  Baseball Game/extra.js
  Baseball Game/index.html
  Baseball Game/manifest.json
  Baseball Game/script.js
  Baseball Game/style.css
Labels: gssoc, level2

#2383 Added typewriter project
  Fun Typewriter/index.css
  Fun Typewriter/index.html
  Fun Typewriter/index.js
  Fun Typewriter/manifest.json
Labels: gssoc, level1

#2377 Solved #2373- Hexempire game extension
  Hexempire/index.html
  Hexempire/manifest.json
  Hexempire/script.js
  Hexempire/styles.css
Labels: gssoc, level2

#2376 added an extension for color memory challenge.
  Color Memory Challenge/index.html
  Color Memory Challenge/manifest.json
  Color Memory Challenge/script.js
  Color Memory Challenge/style.css
Labels: gssoc, level1

#2359 Added infinite cars game
  Infinite Cars/LICENSE
  Infinite Cars/assets/audios/accelerate.wav
  Infinite Cars/assets/audios/crashed.wav
  Infinite Cars/assets/audios/drive.wav
  Infinite Cars/assets/audios/overtake.wav
  Infinite Cars/assets/audios/select.wav
  Infinite Cars/assets/audios/start.wav
  Infinite Cars/assets/fonts/LuckiestGuy-Regular.ttf
  Infinite Cars/assets/icons/infinite-cars-icon-android-144x144.png
  Infinite Cars/assets/icons/infinite-cars-icon-android-192x192.png
  Infinite Cars/assets/icons/infinite-cars-icon-android-36x36.png
  Infinite Cars/assets/icons/infinite-cars-icon-android-48x48.png
  Infinite Cars/assets/icons/infinite-cars-icon-android-72x72.png
  Infinite Cars/assets/icons/infinite-cars-icon-android-96x96.png
  Infinite Cars/assets/images/infinite-cars-character.png
  Infinite Cars/assets/images/infinite-cars-computer.png
  Infinite Cars/assets/images/infinite-cars-explosion.png
  Infinite Cars/assets/images/infinite-cars-flower.png
  Infinite Cars/assets/images/infinite-cars-grass.png
  Infinite Cars/assets/images/infinite-cars-left-gutter.png
  Infinite Cars/assets/images/infinite-cars-left-road.png
  Infinite Cars/assets/images/infinite-cars-middle-road.png
  Infinite Cars/assets/images/infinite-cars-right-gutter.png
  Infinite Cars/assets/images/infinite-cars-right-road.png
  Infinite Cars/assets/images/infinite-cars-road-cone.png
  Infinite Cars/assets/images/infinite-cars-sound.png
  Infinite Cars/assets/images/infinite-cars-stop-light.png
  Infinite Cars/assets/images/infinite-cars-tree.png
  Infinite Cars/background.js
  Infinite Cars/index.html
  Infinite Cars/mainfest.json
  Infinite Cars/options.html
  Infinite Cars/scripts/includes/Constants.js
  Infinite Cars/scripts/includes/Methods.js
  Infinite Cars/scripts/infinite-cars.js
  Infinite Cars/scripts/infinite-cars.processed.js
  Infinite Cars/scripts/libs/phaser.min.js
  Infinite Cars/scripts/scenes/GameScene.js
  Infinite Cars/scripts/scenes/LoadingScene.js
  Infinite Cars/scripts/scenes/MainScene.js
  Infinite Cars/styles/infinite-cars.css
  Infinite Cars/styles/infinite-cars.processed.css
Labels: gssoc, level2

#2369 add trio match game
  Trio Match/README.md
  Trio Match/Trio_Match.png
  Trio Match/index.html
  Trio Match/manifest.json
  Trio Match/script.js
  Trio Match/style.css
Labels: gssoc, level2

#2354 add planet defence game
  Planet Defense/README.md
  Planet Defense/index.html
  Planet Defense/manifest.json
  Planet Defense/script.js
  Planet Defense/space.jpg
  Planet Defense/style.css
  README.md
Labels: gssoc, level2

#2340 Add Open The Lock
  Open The Lock/README.md
  Open The Lock/index.html
  Open The Lock/manifest.json
  Open The Lock/zepto.min.js
Labels: gssoc, level2

#2357 New: Hit Bugs with Sound Effects, Music and add timer !
  BugEliminator/app.html
  BugEliminator/background_music.mp3
  BugEliminator/estilo.css
  BugEliminator/fim_de_jogo.html
  BugEliminator/game-over.mp3
  BugEliminator/icon.png
  BugEliminator/img/bg.jpg
  BugEliminator/img/coracao_cheio.png
  BugEliminator/img/coracao_vazio.png
  BugEliminator/img/game_over.png
  BugEliminator/img/mata_mosquito.png
  BugEliminator/img/mosca.png
  BugEliminator/index.html
  BugEliminator/jogo.js
  BugEliminator/mosquito_hit.mp3
  BugEliminator/vitoria.html
Labels: gssoc, level1

#2393 added image converter tool
  Image Converter/manifest.json
  Image Converter/popup.css
  Image Converter/popup.html
  Image Converter/popup.js
  README.md
Labels: gssoc, level1

#2399 Added Goal rush game
  Goal Rush/Readme.md
  Goal Rush/css/style.css
  Goal Rush/img/01.png
  Goal Rush/img/02.png
  Goal Rush/img/03.png
  Goal Rush/img/04.png
  Goal Rush/img/awayPlayer.png
  Goal Rush/img/background.png
  Goal Rush/img/help.png
  Goal Rush/img/homePlayer.png
  Goal Rush/img/pitch3.png
  Goal Rush/img/splash.png
  Goal Rush/index.html
  Goal Rush/js/SAT.js
  Goal Rush/js/football.js
  Goal Rush/manifest.json
Labels: gssoc, level2

#2400 Added MyMuzie
  MyMuzie/background.js
  MyMuzie/content.js
  MyMuzie/manifest.json
  MyMuzie/popup.html
  MyMuzie/popup.js
Labels: gssoc, level2

#2401 Added Mouse maze
  Mouse Maze/background.js
  Mouse Maze/content.js
  Mouse Maze/manifest.json
  Mouse Maze/popup.html
  Mouse Maze/popup.js
Labels: gssoc, level2

#2403 Added critical point calculator
  Critical Point Calculator/README.md
  Critical Point Calculator/cp.png
  Critical Point Calculator/index.html
  Critical Point Calculator/manifest.json
  Critical Point Calculator/script.js
  Critical Point Calculator/style.css
Labels: gssoc, level1

#2407 add circular motion calculator
  Circular Motion Calculator/background.webp
  Circular Motion Calculator/image.png
  Circular Motion Calculator/index.html
  Circular Motion Calculator/manifest.json
  Circular Motion Calculator/script.js
  Circular Motion Calculator/styles.css
Labels: gssoc, level2

#2392 added random paragraph generator
  Typing Speed Check/manifest.json
  Typing Speed Check/scripts/paragraphs.js
  Typing Speed Check/scripts/script.js
Labels: gssoc, level2

#2385 Added 2d distance calci
  2D Distance Calculator/Readme.md
  2D Distance Calculator/index.html
  2D Distance Calculator/manifest.json
  2D Distance Calculator/script.js
  2D Distance Calculator/style.css
Labels: gssoc, level1

#2381 add hcf calculator
  HCF Calculator/Readme.md
  HCF Calculator/image.png
  HCF Calculator/index.html
  HCF Calculator/manifest.json
  HCF Calculator/script.js
  HCF Calculator/styles.css
Labels: gssoc, level1

#2410 Added golf game extension
  Golf Game Extension/Assets/Golf.jpeg
  Golf Game Extension/Assets/Map_Desert_2.png
  Golf Game Extension/Assets/Map_Plains_2.png
  Golf Game Extension/Assets/Premium Vector _ Golf course background in flat style.jpeg
  Golf Game Extension/Assets/ball_white.png
  Golf Game Extension/Assets/course1.png
  Golf Game Extension/Assets/hole_1.png
  Golf Game Extension/Assets/home_background_1.jpg
  Golf Game Extension/Assets/home_background_2.jpg
  Golf Game Extension/Assets/home_background_3.jpg
  Golf Game Extension/Assets/speed_arrow_1.png
  Golf Game Extension/Assets/stony_texture_1.jpg
  Golf Game Extension/Assets/stony_texture_2 trail.jpg
  Golf Game Extension/Assets/stony_texture_2.jpg
  Golf Game Extension/Assets/stony_texture_3.jpg
  Golf Game Extension/Designs/Home_1.fig
  Golf Game Extension/Golf.jpeg
  Golf Game Extension/README.md
  Golf Game Extension/courses/course1.html
  Golf Game Extension/courses/course1.js
  Golf Game Extension/courses/course2.html
  Golf Game Extension/courses/course2.js
  Golf Game Extension/courses/leaderboard.html
  Golf Game Extension/index.html
  Golf Game Extension/manifest.json
  Golf Game Extension/script.js
  Golf Game Extension/style.css
Labels: gssoc, level2

#2413 Added Emirp Calculator
  Emirp Calculator/index.html
  Emirp Calculator/manifest.json
  Emirp Calculator/script.js
  Emirp Calculator/style.css
Labels: gssoc, level2

#2414 Added Cryptocurrency Calculator
  Cryptocurrency Calculator/index.html
  Cryptocurrency Calculator/manifest.json
  Cryptocurrency Calculator/script.js
  Cryptocurrency Calculator/style.css
Labels: gssoc, level2

#2422 Added virus game extension
  Virus Game Extension/README.md
  Virus Game Extension/game.png
  Virus Game Extension/index.html
  Virus Game Extension/manifest.json
Labels: gssoc, level2

#2423 add ideal gas calculator
  Ideal Gas Calculator/calc.png
  Ideal Gas Calculator/image.jpg
  Ideal Gas Calculator/index.html
  Ideal Gas Calculator/manifest.json
  Ideal Gas Calculator/script.js
  Ideal Gas Calculator/style.css
Labels: gssoc, level2

#2424 Add guess the pokemon game
  Guess The Pokemon Game Extension/Assets/images/background.jpg
  Guess The Pokemon Game Extension/Assets/sounds/correct.mp3
  Guess The Pokemon Game Extension/Assets/sounds/wrong.mp3
  Guess The Pokemon Game Extension/README.md
  Guess The Pokemon Game Extension/icon.png
  Guess The Pokemon Game Extension/index.html
  Guess The Pokemon Game Extension/manifest.json
  Guess The Pokemon Game Extension/script.js
  Guess The Pokemon Game Extension/style.css
Labels: gssoc, level2

#2428 Added Moon phase display extension
  Moon Phase Calculator/assets/first-quarter.png
  Moon Phase Calculator/assets/full-moon.png
  Moon Phase Calculator/assets/last-quarter.png
  Moon Phase Calculator/assets/new-moon.png
  Moon Phase Calculator/assets/waning-crescent.png
  Moon Phase Calculator/assets/waning-gibbous.png
  Moon Phase Calculator/assets/waxing-cresent.png
  Moon Phase Calculator/assets/waxing-gibbous.png
  Moon Phase Calculator/icons/icon128.png
  Moon Phase Calculator/icons/icon16.png
  Moon Phase Calculator/icons/icon32.png
  Moon Phase Calculator/icons/icon48.png
  Moon Phase Calculator/manifest.json
  Moon Phase Calculator/popup.css
  Moon Phase Calculator/popup.html
  Moon Phase Calculator/popup.js
  Moon Phase Calculator/popup.min.js
Labels: gssoc, level2

#2438 Added Arkanoid Game
  Arkanoid Game/README.md
  Arkanoid Game/game-over.png
  Arkanoid Game/game.png
  Arkanoid Game/index.html
  Arkanoid Game/manifest.json
  Arkanoid Game/script.js
  Arkanoid Game/style.css
Labels: gssoc, level2

#2440 Added Population Predictor Extension
  Population Predictor/icons/icon128.png
  Population Predictor/icons/icon16.png
  Population Predictor/icons/icon32.png
  Population Predictor/icons/icon48.png
  Population Predictor/manifest.json
  Population Predictor/popup.css
  Population Predictor/popup.html
  Population Predictor/popup.js
  Population Predictor/popup.min.js
Labels: gssoc, level1

#2444 added aptitude test extension
  Aptitute Test Extension/icon.png
  Aptitute Test Extension/index.html
  Aptitute Test Extension/manifest.json
  Aptitute Test Extension/script.js
  Aptitute Test Extension/style.css
Labels: gssoc, level2

#2446 Added Ebitda calculator
  EBITDA Calculator/Readme.md
  EBITDA Calculator/index.html
  EBITDA Calculator/script.js
  EBITDA Calculator/style.css
Labels: gssoc, level2

#2450 added indian history quiz extension
  Indian History Quiz Extension/icon.png
  Indian History Quiz Extension/index.html
  Indian History Quiz Extension/manifest.json
  Indian History Quiz Extension/script.js
  Indian History Quiz Extension/style.css
Labels: gssoc, level2

#2457 Added Acrobat
  Acrobat/index.html
  Acrobat/manifest.json
  Acrobat/script.js
  Acrobat/styles.css
Labels: gssoc, level2

#2458 Pixel Smash Extension
  Pixel Smash/game.js
  Pixel Smash/icon.png
  Pixel Smash/index.html
  Pixel Smash/manifest.json
  Pixel Smash/styles.css
Labels: gssoc, level2

#2459 resume builder 2
  Resume Builder-2/index.html
  Resume Builder-2/mainfest.json
  Resume Builder-2/script.js
  Resume Builder-2/style.css
Labels: gssoc, level1

#2460 Ping Pong game extension added
  Ping Pong Game/index.html
  Ping Pong Game/manifest.json
  Ping Pong Game/script.js
  Ping Pong Game/style.css
Labels: gssoc, level2

#2447 Added Hashing Calculator
  Hashing Calculator/Readme.md
  Hashing Calculator/index.html
  Hashing Calculator/manifest.json
  Hashing Calculator/script.js
  Hashing Calculator/style.css
Labels: gssoc, level2

#2445 Added Special Number Checker
  Special Number Checker/index.html
  Special Number Checker/manifest.json
  Special Number Checker/script.js
  Special Number Checker/style.css
Labels: gssoc, level2

#2466 Russian Roulette Extension
  Russian Roulette/icon.png
  Russian Roulette/index.html
  Russian Roulette/mainfest.json
  Russian Roulette/script.js
  Russian Roulette/styles.css
Labels: gssoc, level2

#2475 Poker Game Extension
  Poker Game Extension/icon.png
  Poker Game Extension/index.html
  Poker Game Extension/manifest.json
  Poker Game Extension/script.js
  Poker Game Extension/styles.css
Labels: gssoc, level2

#2476 Physics Quiz Extension
  Physics Quiz/icon.png
  Physics Quiz/index.html
  Physics Quiz/manifest.json
  Physics Quiz/script.js
  Physics Quiz/styles.css
Labels: gssoc, level1
