Repository Sulagna-Dutta-Roy/GGExtensions, pull requests merged in 2024-05, with the labels that each got.

#18 Updated README and LEARN
  LEARN.md
  README.md
Labels: GSSoC'24, Level 1

#30 updated readme file
  README.md
Labels: gssoc, level1

#35 Todo app extension using JS
  ToDo JS Extension/index.html
  ToDo JS Extension/manifest.json
  ToDo JS Extension/scripts/script.js
  ToDo JS Extension/src/bg.jpg
  ToDo JS Extension/src/style.css
  ToDo JS Extension/src/todo.png
Labels: gssoc, level1

#51 Update/code line
  README.md
Labels: bug, gssoc, level1

#41 Update README.md contribution section
  README.md
Labels: gssoc, level1

#43 Captcha validator extension using JS
  Capcha Generator/index.html
  Capcha Generator/manifest.json
  Capcha Generator/scripts/script.js
  Capcha Generator/src/bg.jpg
  Capcha Generator/src/demoCaptcha.jpeg
  Capcha Generator/src/style.css
Labels: gssoc, level2

#81 Update
  ToDo JS Extension/index.html
  ToDo JS Extension/logo.png
  ToDo JS Extension/manifest.json
  ToDo JS Extension/scripts/script.js
  ToDo JS Extension/src/style.css
Labels: gssoc, level1

#86 Added Malware Detection Extension
  Malware Detection Extension/Script/popup.js
  Malware Detection Extension/icon.png
  Malware Detection Extension/index.html
  Malware Detection Extension/manifest.json
  Malware Detection Extension/src/style.css
Labels: gssoc, level1

#93 Dictionary feature
  Dictionary Extension/manifest.json
  Dictionary Extension/scripts/background.js
  Dictionary Extension/scripts/content.js
  Dictionary Extension/scripts/sweetalert.js
  Dictionary Extension/src/dictionary.png
Labels: gssoc, level2

#94 Adding the Important Text highlighter and Note taking Extension
  Important Text Highlighter/background.js
  Important Text Highlighter/content.js
  Important Text Highlighter/icons/icon.png
  Important Text Highlighter/manifest.json
  Important Text Highlighter/popup.css
  Important Text Highlighter/popup.html
  Important Text Highlighter/popup.js
Labels: gssoc, level1

#104 Added Playable PIANO Extension
  Playable PIANO/index.html
  Playable PIANO/manifest.json
  Playable PIANO/scripts/script.js
  Playable PIANO/src/style.css
  Playable PIANO/tunes/;.wav
  Playable PIANO/tunes/a.wav
  Playable PIANO/tunes/d.wav
  Playable PIANO/tunes/e.wav
  Playable PIANO/tunes/f.wav
  Playable PIANO/tunes/g.wav
  Playable PIANO/tunes/h.wav
  Playable PIANO/tunes/j.wav
  Playable PIANO/tunes/k.wav
  Playable PIANO/tunes/l.wav
  Playable PIANO/tunes/o.wav
  Playable PIANO/tunes/p.wav
  Playable PIANO/tunes/s.wav
  Playable PIANO/tunes/t.wav
  Playable PIANO/tunes/u.wav
  Playable PIANO/tunes/w.wav
  Playable PIANO/tunes/y.wav
Labels: gssoc, level3

#110 Created Currency converter extension
  Currency Converter/index.html
  Currency Converter/js/country-list.js
  Currency Converter/js/script.js
  Currency Converter/manifest.json
  Currency Converter/style.css
Labels: gssoc, level2

#113 Created Quote Generator Extension
  Quote Generator/index.html
  Quote Generator/manifest.json
  Quote Generator/scripts/script.js
  Quote Generator/src/bg.jpg
  Quote Generator/src/demo.png
  Quote Generator/src/style.css
Labels: gssoc, level2

#115 Dark mode extension
  Darkmode Extension/.DS_Store
  Darkmode Extension/images/moon.png
  Darkmode Extension/manifest.json
  Darkmode Extension/popup.html
  Darkmode Extension/popup.js
Labels: gssoc, level2

#130 Enhanced the UI of the Website
  Number Guess Game JS Extension/scripts/script.js
  Number Guess Game JS Extension/src/style.css
Labels: gssoc, level1

#131 Delete Button code Changes in todo js
  ToDo JS Extension/scripts/script.js
Labels: bug, gssoc, level1

#134 Added alert features in captcha generator.
  Capcha Generator/index.html
  Capcha Generator/scripts/script.js
Labels: gssoc, level1

#137 Fixes #100 : Stopwatch
  Stopwatch/index.html
  Stopwatch/scripts/script.js
  Stopwatch/src/style.css
Labels: gssoc, level1

#129 Created TextToSpeech Extension Files
  Text To Speech/index.html
  Text To Speech/manifest.json
  Text To Speech/scripts/script.js
  Text To Speech/src/style.css
Labels: gssoc, level1

#139 Fixes #116 : Calculator
  Calculator/index.html
  Calculator/manifest.json
  Calculator/scripts/script.js
  Calculator/src/style.css
Labels: gssoc, level1

#146 Fixes #109 : QR Code Generator
  QR Code Generator/arrow.png
  QR Code Generator/index.html
  QR Code Generator/manifest.json
  QR Code Generator/scripts/script.js
  QR Code Generator/src/style.css
Labels: gssoc, level2

#154 Fixes #136 : Tic-Tac-Toe
  Tic-Tac-Toe Game/index.html
  Tic-Tac-Toe Game/manifest.json
  Tic-Tac-Toe Game/scripts/script.js
  Tic-Tac-Toe Game/src/style.css
Labels: gssoc, level2

#157 Fixes #108 : Expense Tracker
  Expense Tracker/index.html
  Expense Tracker/manifest.json
  Expense Tracker/scripts/script.js
  Expense Tracker/src/style.css
Labels: gssoc, level2

#169 Created dynamic calender extension
  Dynamic Calender/index.html
  Dynamic Calender/manifest.json
  Dynamic Calender/scripts/script.js
  Dynamic Calender/src/style.css
Labels: gssoc, level1

#170 Fixes #135 : Barcode Generator
  Barcode Generator/index.html
  Barcode Generator/manifest.json
  Barcode Generator/scripts/script.js
  Barcode Generator/src/style.css
Labels: gssoc, level1

#171 Fixes #118 : Memory Game
  Memory Game/assets/anaconda.png
  Memory Game/assets/bee.png
  Memory Game/assets/chameleon.png
  Memory Game/assets/cockatoo.png
  Memory Game/assets/crocodile.png
  Memory Game/assets/gorilla.png
  Memory Game/assets/macaw.png
  Memory Game/assets/monkey.png
  Memory Game/assets/piranha.png
  Memory Game/assets/sloth.png
  Memory Game/assets/tiger.png
  Memory Game/assets/toucan.png
  Memory Game/index.html
  Memory Game/manifest.json
  Memory Game/scripts/script.js
  Memory Game/src/style.css
Labels: gssoc, level2

#167 script.js (song tracker) improvement in code in efficiency
  Song Tracker/scripts/script.js
Labels: gssoc, level1

#183 Added the file CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#179 Added YouTube Video Summariser
  YouTube Video Summariser/README.md
  YouTube Video Summariser/app.py
  YouTube Video Summariser/extension/images/icon.png
  YouTube Video Summariser/extension/manifest.json
  YouTube Video Summariser/extension/popup.html
  YouTube Video Summariser/extension/popup.js
Labels: gssoc, level1

#189 Weather Report : Created manifest.json
  Weather Report/manifest.json
Labels: gssoc, level1

#190 Stopwatch : Created manifest.json
  Stopwatch/manifest.json
Labels: gssoc, level1

#193 Fixes #133 : Movie Finder
  Movie Finder/assets/image_not_found.png
  Movie Finder/index.html
  Movie Finder/manifest.json
  Movie Finder/scripts/script.js
  Movie Finder/src/style.css
Labels: gssoc, level2

#196 Added YouTube Bookmarker
  YouTube Bookmarker/assets/bookmark.png
  YouTube Bookmarker/assets/delete.png
  YouTube Bookmarker/assets/ext-icon.png
  YouTube Bookmarker/assets/play.png
  YouTube Bookmarker/assets/save.png
  YouTube Bookmarker/background.js
  YouTube Bookmarker/contentScript.js
  YouTube Bookmarker/manifest.json
  YouTube Bookmarker/popup.css
  YouTube Bookmarker/popup.html
  YouTube Bookmarker/popup.js
  YouTube Bookmarker/utils.js
Labels: gssoc, level2

#202 Added Strong Pass Extension
  Strong Password Extension/index.html
  Strong Password Extension/manifest.json
  Strong Password Extension/scripts/script.js
  Strong Password Extension/src/style.css
Labels: gssoc, level2

#194 Fixes #141 : Food Recipe
  Food Recipe/index.html
  Food Recipe/manifest.json
  Food Recipe/scripts/script.js
  Food Recipe/src/style.css
Labels: gssoc, level2

#203 Auto Commenting Feat for PR Raised
  .github/workflows/autocomment-pr-raise.yml
Labels: gssoc, level2

#204 Fixes #142 : Bill Splitter
  Bill Splitter/index.html
  Bill Splitter/manifest.json
  Bill Splitter/scripts/script.js
  Bill Splitter/src/style.css
Labels: gssoc, level2

#205 Auto Commenting Feat for PR Merged
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, level3

#208 Auto Commenting Feat for Issue Creation
  .github/workflows/autocomment-issue.yml
Labels: gssoc, level2

#214 Added World Clock Extension
  World Clock Extension/index.html
  World Clock Extension/manifest.json
  World Clock Extension/scripts/script.js
  World Clock Extension/src/styles.css
Labels: gssoc, level2

#219 Feature Request: Audio CAPTCHA and CAPTCHA History
  Capcha Generator/index.html
  Capcha Generator/manifest.json
  Capcha Generator/scripts/script.js
Labels: gssoc, level1

#209 Celebrity Icon Extension
  Celebrity/Content.js
  Celebrity/manifest.json
Labels: gssoc, level1

#212 Add new download button feature
  QR Code Generator/scripts/script.js
Labels: gssoc, level1

#222 Created close-old-issue.yml
  .github/workflows/close-old-issue.yml
Labels: gssoc, level2

#224 Created QR Reader extension
  QR Code Reader/index.html
  QR Code Reader/manifest.json
  QR Code Reader/scripts/script.js
  QR Code Reader/src/style.css
Labels: gssoc, level1

#223 Created close-old-pr.yml
  .github/workflows/close-old-pr.yml
Labels: gssoc, level2

#226 Added animated dark mode toggle
  Darkmode Extension/popup.html
  Darkmode Extension/popup.js
Labels: gssoc, level2

#229 Created typing speed check extension
  Typing Speed Check/index.html
  Typing Speed Check/manifest.json
  Typing Speed Check/scripts/paragraphs.js
  Typing Speed Check/scripts/script.js
  Typing Speed Check/src/style.css
Labels: gssoc, level2

#238 Added modularity to code along with error handling
  Text To Speech/scripts/script.js
Labels: gssoc, level2

#239 Fixes #187 : Minesweeper Game
  Minesweeper Game/assets/Minesweeper.jpg
  Minesweeper Game/index.html
  Minesweeper Game/manifest.json
  Minesweeper Game/scripts/script.js
  Minesweeper Game/src/style.css
Labels: gssoc, level2

#240 Fixes #186 : Word Scramble Game
  Word Scramble Game/index.html
  Word Scramble Game/manifest.json
  Word Scramble Game/scripts/script.js
  Word Scramble Game/scripts/words.js
  Word Scramble Game/src/style.css
Labels: gssoc, level2

#242 Fixes #160: Length Converter JS Extension
  Length Converter JS Extension/img/background-blue-aesthetic-flowers.jpg
  Length Converter JS Extension/js/length-converter.js
  Length Converter JS Extension/js/project-common.js
  Length Converter JS Extension/main.html
  Length Converter JS Extension/manifest.json
  Length Converter JS Extension/scripts/length-converter.js
  Length Converter JS Extension/scripts/project-common.js
  Length Converter JS Extension/src/background-blue-aesthetic-flowers.jpg
  Length Converter JS Extension/src/icon-128.png
  Length Converter JS Extension/src/icon-16.png
  Length Converter JS Extension/src/icon-32.png
  Length Converter JS Extension/src/icon-48.png
  Length Converter JS Extension/src/style.css
  Length Converter JS Extension/style.css
Labels: gssoc, level3

#243 Fixes #147 : Resume Builder
  Resume Builder/index.html
  Resume Builder/manifest.json
  Resume Builder/scripts/app.js
  Resume Builder/scripts/script.js
  Resume Builder/src/style.css
Labels: gssoc, level3

#247 AI-Powered Website Content Summarizer (Browser Extension) #132
  Website Content Summarizer/Procfile
  Website Content Summarizer/README.md
  Website Content Summarizer/app.py
  Website Content Summarizer/icon.png
  Website Content Summarizer/images/icon.png
  Website Content Summarizer/manifest.json
  Website Content Summarizer/popup.css
  Website Content Summarizer/popup.html
  Website Content Summarizer/popup.js
  Website Content Summarizer/requirements.txt
Labels: gssoc, level2

#255 Update style.css
  Calculator/src/style.css
Labels: gssoc, level1

#258 feat: Fixes:#148 Add Bookmark Manager Extension
  Bookmark Extension/background.js
  Bookmark Extension/icon128.png
  Bookmark Extension/icon16.png
  Bookmark Extension/icon48.png
  Bookmark Extension/manifest.json
  Bookmark Extension/options.html
  Bookmark Extension/popup.html
  Bookmark Extension/popup.js
  Bookmark Extension/styles.css
Labels: gssoc, level2

#232 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#262 Fixes #188 : Whack-a-mole game
  Whack-a-mole/assets/hammer.png
  Whack-a-mole/assets/mole.png
  Whack-a-mole/index.html
  Whack-a-mole/manifest.json
  Whack-a-mole/scripts/script.js
  Whack-a-mole/src/style.css
Labels: gssoc, level2

#263 Added Reset button and scores of CPU and User
  Rock Paper Scissors/index.html
  Rock Paper Scissors/scripts/script.js
  Rock Paper Scissors/src/style.css
Labels: gssoc, level2

#267 Add Bookmark Functionality for GitHub URLs to Browser Bookmarks
  Github Bookmark Extension/icons/icon128.png
  Github Bookmark Extension/icons/icon16.png
  Github Bookmark Extension/icons/icon48.png
  Github Bookmark Extension/manifest.json
  Github Bookmark Extension/popup.css
  Github Bookmark Extension/popup.html
  Github Bookmark Extension/popup.js
Labels: gssoc, level2

#275 Fixes #159 : Chatbot
  Chatbot/index.html
  Chatbot/manifest.json
  Chatbot/scripts/script.js
  Chatbot/src/style.css
Labels: gssoc, level2

#276 Added Productive Tab Manager
  Productive Tab Manager/icon.png
  Productive Tab Manager/manifest.json
  Productive Tab Manager/popup.css
  Productive Tab Manager/popup.html
  Productive Tab Manager/popup.js
Labels: gssoc, level2

#280 Flappy Bird Game JS Extension
  Flappy Bird Game/images/Bird-128.png
  Flappy Bird Game/images/Bird-16.png
  Flappy Bird Game/images/Bird-32.png
  Flappy Bird Game/images/Bird-48.png
  Flappy Bird Game/images/Bird-I.png
  Flappy Bird Game/images/Bird-II.png
  Flappy Bird Game/images/background-img.png
  Flappy Bird Game/index.html
  Flappy Bird Game/manifest.json
  Flappy Bird Game/script.js
  Flappy Bird Game/style.css
Labels: gssoc, level3

#284 Fixes #279
  Calculator/index.html
  Calculator/scripts/script.js
Labels: gssoc, level1

#285 Feature : Full Page Screenshot for Chrome Extension
  Full Page Screenshot/index.html
  Full Page Screenshot/manifest.json
  Full Page Screenshot/scripts/background.js
  Full Page Screenshot/scripts/popup.js
  Full Page Screenshot/src/icon.jpg
  Full Page Screenshot/src/popup.css
Labels: gssoc, level1

#307 Fixes #155
  Text to Image Generator/index.html
  Text to Image Generator/manifest.json
  Text to Image Generator/scripts/script.js
  Text to Image Generator/src/style.css
Labels: gssoc, level2

#304 added autocommenting feat for closing an issue
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level3

#291 Added Youtube Video Downloader Extension
  YouTube Video Downloader/background.js
  YouTube Video Downloader/icon128.png
  YouTube Video Downloader/icon16.png
  YouTube Video Downloader/icon48.png
  YouTube Video Downloader/manifest.json
  YouTube Video Downloader/package-lock.json
  YouTube Video Downloader/package.json
  YouTube Video Downloader/popup.css
  YouTube Video Downloader/popup.html
  YouTube Video Downloader/popup.js
  YouTube Video Downloader/server.js
Labels: gssoc, level2

#292 Enhanced Visual Design for Strong Password Extension
  Strong Password Extension/src/style.css
Labels: gssoc, level1

#293 Corrected the display of Play Again button in checkDraw function
  Tic-Tac-Toe Game/scripts/script.js
Labels: bug, gssoc, level2

#294 Fix delete button functionality
  ToDo JS Extension/scripts/script.js
Labels: bug, gssoc, level2

#301 Reset modal state when starting a new game
  Word Scramble Game/scripts/script.js
Labels: gssoc, level2

#308 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#311 Screenshot Extension
  SreenShot Extension/manifest.json
  SreenShot Extension/popup.html
  SreenShot Extension/scripts/popup.js
  SreenShot Extension/src/popup.css
Labels: gssoc, level1

#286 Add Winner Notification and Play Again Functionality to Rock Paper Scissors Game
  Rock Paper Scissors/index.html
  Rock Paper Scissors/scripts/script.js
  Rock Paper Scissors/src/style.css
Labels: gssoc, level3

#302 Pictionary game extension
  Pictionary Game/Index.html
  Pictionary Game/manifest.json
  Pictionary Game/scripts/script.js
  Pictionary Game/src/styles.css
Labels: gssoc, level2

#313 All the nations in the World clock extension show the same time
  World Clock Extension/scripts/script.js
Labels: bug, gssoc, level2

#315 Fixes #278
  Calculator/index.html
  Calculator/scripts/script.js
Labels: gssoc, level2

#317 Add "Fact of the Day" Browser Extension
  Fact of the day/icons/icon.png
  Fact of the day/manifest.json
  Fact of the day/popup.html
  Fact of the day/popup.js
  Fact of the day/style.css
Labels: gssoc, level2

#305 Added Email Validator App
  Email Validator/css/style.css
  Email Validator/img/email.svg
  Email Validator/img/loading.svg
  Email Validator/index.html
  Email Validator/js/index.js
  Email Validator/manifest.json
Labels: gssoc, level1

#266 Focus Extension
  Focus/index.js
  Focus/indexDev.js
  Focus/manifest.json
  Focus/package-lock.json
  Focus/package.json
  Focus/style.css
  focus/index.js
  focus/indexDev.js
  focus/manifest.json
  focus/package-lock.json
  focus/package.json
  focus/style.css
Labels: gssoc, level1

#295 [feature] URL Shortener
  URL Shortener/index.html
  URL Shortener/script.js
Labels: gssoc, level2

#320 Added the netwrok speed test extension
  Network speed/icon.png
  Network speed/manifest.json
  Network speed/popup.css
  Network speed/popup.html
  Network speed/popup.js
Labels: gssoc, level2

#323 Spelling mistake in the directory name
  Screenshot Extension/manifest.json
  Screenshot Extension/popup.html
  Screenshot Extension/scripts/popup.js
  Screenshot Extension/src/popup.css
Labels: gssoc, level1

#327 Fixes #72 : Markdown Previewer
  Markdown Previewer/index.html
  Markdown Previewer/manifest.json
  Markdown Previewer/scripts/export.js
  Markdown Previewer/scripts/script.js
  Markdown Previewer/src/style.css
Labels: gssoc, level3

#329 Fixes #200 : Image Editor
  Image Editor/assets/blur.png
  Image Editor/assets/brightnss.png
  Image Editor/assets/contrast.png
  Image Editor/assets/flip.png
  Image Editor/assets/invert.png
  Image Editor/assets/opactiy.png
  Image Editor/assets/rotateleft.png
  Image Editor/assets/rotateright.png
  Image Editor/assets/upload.png
  Image Editor/index.html
  Image Editor/manifest.json
  Image Editor/scripts/script.js
  Image Editor/src/style.css
Labels: gssoc, level2

#335 Drink Water Extension
  Drink Water Extension/background.js
  Drink Water Extension/icons/128.png
  Drink Water Extension/icons/16.png
  Drink Water Extension/icons/32.png
  Drink Water Extension/icons/48.png
  Drink Water Extension/index.html
  Drink Water Extension/index.js
  Drink Water Extension/manifest.json
  Drink Water Extension/style.css
Labels: gssoc, level1

#337 Fixes #314
  Flappy Bird Game/style.css
Labels: gssoc, level1

#347 added workflow for closing issues on merging PRs
  .github/workflows/close-on-merge.yml
Labels: gssoc, level3

#359 Fixes#172: Added extension for Icon
  Icon/Content.js
  Icon/manifest.json
Labels: gssoc, level2

#336 Emoji keyboard added
  Emoji Keyboard/image128.png
  Emoji Keyboard/image16.png
  Emoji Keyboard/image32.png
  Emoji Keyboard/image48.png
  Emoji Keyboard/manifest.json
  Emoji Keyboard/marquee1400.png
  Emoji Keyboard/popup.css
  Emoji Keyboard/popup.html
  Emoji Keyboard/popup.js
Labels: gssoc, level1

#349 Added Browser History Cleaner Extension
  Browser History Cleaner/icon.png
  Browser History Cleaner/manifest.json
  Browser History Cleaner/popup.css
  Browser History Cleaner/popup.html
  Browser History Cleaner/popup.js
Labels: gssoc, level2

#350 Added Fun Trivia Extension
  Fun Trivia Extension/icon.png
  Fun Trivia Extension/manifest.json
  Fun Trivia Extension/popup.css
  Fun Trivia Extension/popup.html
  Fun Trivia Extension/popup.js
Labels: gssoc, level1

#352 My feature:Added a preloader to the extension
  Productive Tab Manager/popup.css
  Productive Tab Manager/popup.html
  Productive Tab Manager/popup.js
  Productive Tab Manager/prelo.gif
Labels: gssoc, level2

#363 Added Pomodoro
  Pomodoro/1.jpg
  Pomodoro/backtowork.mp3
  Pomodoro/break.mp3
  Pomodoro/button-sound.mp3
  Pomodoro/icon16.png
  Pomodoro/manifest.json
  Pomodoro/popup.html
  Pomodoro/script.js
  Pomodoro/style.css
Labels: gssoc, level1

#366 Added styling to the drink water extension
  Drink Water Extension/style.css
Labels: gssoc, level1

#365 Copy and search extension
  Copy and Search Extension/background.js
  Copy and Search Extension/manifest.json
  Copy and Search Extension/popup.html
  Copy and Search Extension/scripts/foreground.js
  Copy and Search Extension/scripts/popup_script.js
  Copy and Search Extension/styles/popup_styles.css
Labels: gssoc, level1

#367 Added Next button in Joke Xpress extension
  Jokes Xpress Extension/all_files/index.html
  Jokes Xpress Extension/all_files/script.js
  Jokes Xpress Extension/all_files/style.css
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/index.html
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/script.js
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/style.css
Labels: gssoc, level2

#369 Swipe Gesture for Month Navigation in Dynamic Calendar Extension
  Dynamic Calender/scripts/script.js
  Dynamic Calender/src/style.css
Labels: gssoc, level2

#370 Revamping of the captcha generator's UI
  Capcha Generator/index.html
  Capcha Generator/src/style.css
Labels: gssoc, level1

#371 add and remove clock enabled
  World Clock Extension/index.html
  World Clock Extension/scripts/script.js
  World Clock Extension/src/styles.css
Labels: gssoc, level2

#372 Added Artwork Showcase extension
  Artwork Showcase/manifest.json
  Artwork Showcase/popup.css
  Artwork Showcase/popup.html
  Artwork Showcase/popup.js
Labels: gssoc, level1

#377 Fixes #198
  Code Editor/assets/CSS.png
  Code Editor/assets/html.png
  Code Editor/assets/js.png
  Code Editor/index.html
  Code Editor/manifest.json
  Code Editor/scripts/script.js
  Code Editor/src/style.css
Labels: gssoc, level2

#303 modified: Number Guess Game JS Extension/src/style.css
  Number Guess Game JS Extension/src/style.css
Labels: bug, gssoc, level1

#375 Added bmi calculator
  BMI Calculator/icon.png
  BMI Calculator/manifest.json
  BMI Calculator/popup.css
  BMI Calculator/popup.html
  BMI Calculator/popup.js
  Focus/index1.js
  Focus/indexDev1.js
  Focus/manifest1.json
  Focus/package-lock1.json
  Focus/package1.json
  Focus/stylee.css
  focus/index.js
  focus/indexDev.js
  focus/manifest.json
  focus/package-lock.json
  focus/package.json
  focus/style.css
Labels: gssoc, level2

#387 AdBlocker Extension
  AdBlocker Extension/background.js
  AdBlocker Extension/icons/logo.png
  AdBlocker Extension/manifest.json
Labels: gssoc, level1

#391 Added Quick Wikipedia Extension
  Quick Wikipedia Search Extension/icon.png
  Quick Wikipedia Search Extension/manifest.json
  Quick Wikipedia Search Extension/popup.css
  Quick Wikipedia Search Extension/popup.html
  Quick Wikipedia Search Extension/popup.js
Labels: gssoc, level2

#394 Added 2048 Game Extension
  2048 Game/icon.png
  2048 Game/manifest.json
  2048 Game/popup.css
  2048 Game/popup.html
  2048 Game/popup.js
Labels: gssoc, level2

#395 Added missing icon image for Barcode Generator extension
  Barcode Generator/images.png
  Barcode Generator/manifest.json
Labels: gssoc, level2

#398 Added Picture of the day extension
  Picture of the day Extension/css/style.css
  Picture of the day Extension/img/diaspora.png
  Picture of the day Extension/img/icon.jpg
  Picture of the day Extension/img/logo128.png
  Picture of the day Extension/img/mastodon.png
  Picture of the day Extension/js/popup.js
  Picture of the day Extension/manifest.json
  Picture of the day Extension/popup.html
Labels: gssoc, level1

#401 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc

#399 Added IT Tax calculator extension
  IT Income Tax Calculator/calculate.js
  IT Income Tax Calculator/it.html
  IT Income Tax Calculator/logo.png
  IT Income Tax Calculator/manifest.json
Labels: gssoc, level2

#407 Fixes#362:Added random quote extension
  Quote/background.js
  Quote/manifest.json
  Quote/popup.html
  Quote/popup.js
  Quote/quotes.png
  Quote/styles.css
Labels: gssoc, level2

#409 Added missing icon image for Bill Splitter
  Bill Splitter/image.png
  Bill Splitter/manifest.json
Labels: gssoc, level2

#411 Added missing icon image for Chatbot extension
  Chatbot/image.png
  Chatbot/manifest.json
Labels: gssoc, level2

#413 Added missing icon image for Code Editor extension
  Code Editor/image.png
  Code Editor/manifest.json
Labels: gssoc, level2

#415 Adjusted the height and width of Barcode Generator Extension
  Barcode Generator/manifest.json
  Barcode Generator/src/style.css
Labels: gssoc, level1

#418 added audio player extension
  Audio Player/images.jpg
  Audio Player/index.html
  Audio Player/manifest.json
  Audio Player/scripts/script.js
  Audio Player/src/style.css
Labels: gssoc, level2

#435 Enhanced the ui and added a analog clock as well
  World Clock Extension/scripts/script.js
  World Clock Extension/src/styles.css
Labels: gssoc, level2

#439 Added Page Finder Text Extension
  Page Text Finder Extension/content.css
  Page Text Finder Extension/content.js
  Page Text Finder Extension/icon.png
  Page Text Finder Extension/manifest.json
  Page Text Finder Extension/popup.html
  Page Text Finder Extension/popup.js
Labels: gssoc, level2

#467 Fix for URL Shortener Extension Load Failure Due to Unreadable Manifest File
  URL Shortener/manifest.json
Labels: gssoc, level1

#423 Adjusted the height and width of chatbot extension
  Chatbot/src/style.css
Labels: gssoc, level1

#425 Adjusted the height and width of code editor
  Code Editor/src/style.css
Labels: gssoc, level1

#465 Adjusted the height and width Capcha generator
  Capcha Generator/src/style.css
Labels: gssoc, level1

#473 Crypto tracker issue solved
  Crypto Tracker Extension/html/main.html
  Live Cricket Extension/manifest.json
Labels: gssoc, level1

#344 added sudoku game extension
  Sudoku Game Extension/index.html
  Sudoku Game Extension/manifest.json
  Sudoku Game Extension/scripts/script.js
  Sudoku Game Extension/src/styles.css
Labels: gssoc, level2

#408 Joke Xpress Extension: Removed Duplicates Folder
  Jokes Xpress Extension/Code_of_conduct.md
  Jokes Xpress Extension/LEARN.md
  Jokes Xpress Extension/LICENSE
  Jokes Xpress Extension/all_files/.github/ISSUE_TEMPLATE/bug_report.md
  Jokes Xpress Extension/all_files/.github/ISSUE_TEMPLATE/feature_request.md
  Jokes Xpress Extension/all_files/.github/Pull_Request_Template.md
  Jokes Xpress Extension/all_files/.github/auto_assign_config.yml
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/.github/ISSUE_TEMPLATE/bug_report.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/.github/ISSUE_TEMPLATE/feature_request.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/.github/Pull_Request_Template.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/.github/auto_assign_config.yml
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/Code_of_conduct.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/LEARN.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/LICENSE
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/README.md
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/index.html
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/logo.png
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/manifest.json
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/script.js
  Jokes Xpress Extension/djj/Jokes Xpress Extension/Jokes Xpress Extension/all files/style.css
  Jokes Xpress Extension/index.html
  Jokes Xpress Extension/logo.png
  Jokes Xpress Extension/manifest.json
  Jokes Xpress Extension/script.js
  Jokes Xpress Extension/style.css
Labels: gssoc, level2

#474 cricket api fixed
  Live Cricket Extension/index.html
  Live Cricket Extension/scripts/script.js
Labels: gssoc, level1

#480 Audio Recorder added
  Audio_Recorder/encoders/Mp3Encoder.min.js
  Audio_Recorder/encoders/Mp3Encoder.min.js.mem
  Audio_Recorder/encoders/WavEncoder.min.js
  Audio_Recorder/html/complete.html
  Audio_Recorder/html/error.html
  Audio_Recorder/html/options.html
  Audio_Recorder/html/popup.html
  Audio_Recorder/icon.png
  Audio_Recorder/js/background.js
  Audio_Recorder/js/options.js
  Audio_Recorder/js/popup.js
  Audio_Recorder/js/worker.js
  Audio_Recorder/manifest.json
  Audio_Recorder/workers/Mp3Worker.js
  Audio_Recorder/workers/WavWorker.js
Labels: gssoc, level1

#481 World scramble game: Fix CSP Error by Replacing Inline Event Handlers with External JavaScript Event Listeners
  Word Scramble Game/index.html
  Word Scramble Game/scripts/script.js
Labels: gssoc, level1

#486 Focus Mate extension is added
  Focus Mate/CSS/navbar.css
  Focus Mate/CSS/pomodoro.css
  Focus Mate/CSS/popup.css
  Focus Mate/CSS/todo_list.css
  Focus Mate/HTML/performance.html
  Focus Mate/HTML/pomodoro.html
  Focus Mate/HTML/popup.html
  Focus Mate/HTML/todo_list.html
  Focus Mate/HTML/website_blocking.html
  Focus Mate/HTML/working_session.html
  Focus Mate/JS/background.js
  Focus Mate/JS/chart.js
  Focus Mate/JS/pomodoro.js
  Focus Mate/JS/popup.js
  Focus Mate/JS/todo_list.js
  Focus Mate/assets/audio/alarm.mp3
  Focus Mate/assets/images/focus_mate.png
  Focus Mate/assets/images/unchecked.png
  Focus Mate/manifest.json
Labels: gssoc, level2

#487 Added Date to day converter extension
  Date to Day/logo.png
  Date to Day/manifest.json
  Date to Day/popup.css
  Date to Day/popup.html
  Date to Day/popup.js
Labels: gssoc, level2

#493 Revamped the interface
  Strong Password Extension/index.html
  Strong Password Extension/src/style.css
Labels: gssoc, level1

#494 Dog Facts Extension
  Dog Facts Extension/Dog.png
  Dog Facts Extension/Dogs.jpg
  Dog Facts Extension/index.html
  Dog Facts Extension/manifest.json
  Dog Facts Extension/script.js
Labels: gssoc, level1

#495 Enhance Music Player UI
  Audio Player/src/style.css
Labels: gssoc, level1

#496 Enhance the Random Quote generator
  Quote/styles.css
Labels: gssoc, level1

#497 Fixing Height and Width Issues in Multiple Extensions
  Expense Tracker/src/style.css
  Food Recipe/src/style.css
  Gradient Generator/src/style.css
  Image Editor/src/style.css
  Markdown Previewer/src/style.css
  Memory Game/manifest.json
  Memory Game/src/style.css
  Minesweeper Game/src/style.css
  Movie Finder/src/style.css
  Number Guess Game JS Extension/src/style.css
  QR Code Generator/src/style.css
  Resume Builder/src/style.css
  Song Tracker/src/style.css
  Tic-Tac-Toe Game/src/style.css
Labels: gssoc, level1

#490 fixes issue #424 now user can understand what he want to write in the barcode box
  Barcode Generator/index.html
Labels: gssoc, level1

#501 added news extension
  News Extension/index.html
  News Extension/manifest.json
  News Extension/scripts/script.js
  News Extension/src/style.css
Labels: gssoc, level2

#504 Anime Quote Extension
  Anime Quote Extension/AnimeWall.jpg
  Anime Quote Extension/index.html
  Anime Quote Extension/logo.png
  Anime Quote Extension/manifest.json
  Anime Quote Extension/script.js
Labels: gssoc, level1

#476 Added weight calculator
  Weight Calculator/icon.png
  Weight Calculator/manifest.json
  Weight Calculator/popup.html
  Weight Calculator/script.js
  Weight Calculator/style.css
  Weight calculator/icon.png
  Weight calculator/manifest.json
  Weight calculator/popup.css
  Weight calculator/popup.html
  Weight calculator/popup.js
Labels: gssoc, level1

#505 Reminder Pro -- Never forget a task with chrom
  Reminder Pro/CSS/popup.css
  Reminder Pro/CSS/styles.css
  Reminder Pro/JS/script.js
  Reminder Pro/assets/ringtone.wav
  Reminder Pro/assets/sass/popup.scss
  Reminder Pro/background.js
  Reminder Pro/contentScript.js
  Reminder Pro/images/wedding-bells_128.png
  Reminder Pro/images/wedding-bells_16.png
  Reminder Pro/images/wedding-bells_32.png
  Reminder Pro/images/wedding-bells_64.png
  Reminder Pro/index.html
  Reminder Pro/manifest.json
  Reminder Pro/package.json
  Reminder Pro/popup.html
  Reminder Pro/reminder_sound_player.py
  Reminder Pro/webpack.mix.js
Labels: gssoc, level2

#510 Added Password Manager Extension
  Password Manager/index.html
  Password Manager/manifest.json
  Password Manager/scripts.js
  Password Manager/styles.css
Labels: gssoc, level1

#512 Added Bingo game extension
  Bingo Game Extension/index.html
  Bingo Game Extension/manifest.json
  Bingo Game Extension/scripts/script.js
  Bingo Game Extension/src/style.css
Labels: gssoc, level2

#515 language translator added
  Language Translator/index.html
  Language Translator/language.js
  Language Translator/manifest.json
  Language Translator/script.js
  Language Translator/style.css
Labels: gssoc, level2

#517 bitcoin price tracler added
  Bitcoin Price Tracker/index.html
  Bitcoin Price Tracker/manifest.json
  Bitcoin Price Tracker/script.js
  Bitcoin Price Tracker/style.css
Labels: gssoc, level2

#518 Curreny Converyter Issue Solved
  Currency Converter/js/script.js
Labels: gssoc, level1

#516 gold silver price tracker added
  Gold Price Tracker/index.html
  Gold Price Tracker/manifest.json
  Gold Price Tracker/script.js
  Gold Price Tracker/style.css
Labels: gssoc, level2

#530 Rick Morty Extension
  Rick Morty Extension/Rick-And-Morty.jpeg
  Rick Morty Extension/index.html
  Rick Morty Extension/logo.png
  Rick Morty Extension/manifest.json
  Rick Morty Extension/script.js
Labels: gssoc, level2

#525 Added Background Remover Extension
  Background Remover Extension/logo.png
  Background Remover Extension/manifest.json
  Background Remover Extension/popup.html
  Background Remover Extension/script.js
  Background Remover Extension/styles.css
  Weight Calculator/icon_renamed.png
  Weight Calculator/manifest_renamed.json
  Weight Calculator/popup_renamed.html
  Weight calculator/icon.png
  Weight calculator/manifest.json
  Weight calculator/popup.html
Labels: gssoc, level2
