Repository Sulagna-Dutta-Roy/GGExtensions, pull requests merged in 2024-06, with the labels that each got.

#648 New Extension - BMI Check
  BMI Check/index.html
  BMI Check/manifest.json
  BMI Check/scripts/script.js
  BMI Check/src/style.css
Labels: gssoc, level1

#658 Added Book Recommendation Extension
  Book Recommendation Extension/book.jpg
  Book Recommendation Extension/book3.png
  Book Recommendation Extension/manifest.json
  Book Recommendation Extension/popup.html
  Book Recommendation Extension/script.js
  Book Recommendation Extension/style.css
Labels: gssoc, level2

#664 leetcode potd generator added
  Leetcode POTD Generator/data.json
  Leetcode POTD Generator/manifest.json
  Leetcode POTD Generator/popup.html
  Leetcode POTD Generator/popup.js
  Leetcode POTD Generator/style.css
  Weight Calculator/icon.png
Labels: gssoc, level3

#665 Calorie Burned Calculator
  Calorie Burned Calculator/icon.png
  Calorie Burned Calculator/manifest.json
  Calorie Burned Calculator/popup.html
  Calorie Burned Calculator/script.js
  Calorie Burned Calculator/style.css
Labels: gssoc, level1

#666 Book Reading Time Extension
  Book Reading Time Extension/icon.png
  Book Reading Time Extension/manifest.json
  Book Reading Time Extension/popup.html
  Book Reading Time Extension/script.js
  Book Reading Time Extension/style.css
Labels: gssoc, level1

#667 Image to link generator extension added
  Image2Link/index.html
  Image2Link/manifest.json
  Image2Link/script.js
  Image2Link/style.css
Labels: gssoc, level1

#669 Heart Rate Extension
  Heart Rate Extension/icon.png
  Heart Rate Extension/manifest.json
  Heart Rate Extension/popup.html
  Heart Rate Extension/script.js
  Heart Rate Extension/style.css
Labels: gssoc, level1

#672 GST Calculator
  GST Calculator/icon.png
  GST Calculator/manifest.json
  GST Calculator/popup.html
  GST Calculator/script.js
  GST Calculator/style.css
Labels: gssoc, level1

#639 determinant calculator
  Determinant Calculator/icons/icon.png
  Determinant Calculator/icons/icon2.png
  Determinant Calculator/icons/icon3.png
  Determinant Calculator/index.html
  Determinant Calculator/manifest.json
  Determinant Calculator/script.js
Labels: gssoc, level2

#675 i have added Word Wander extension
  Word Wander/manifest.json
  Word Wander/popup.html
  Word Wander/popup.js
  Word Wander/styles.css
Labels: gssoc, level1

#683 Added space shooter extension
  Space Shooter/index.html
  Space Shooter/manifest.json
  Space Shooter/script.js
  Space Shooter/style.css
Labels: gssoc, level2

#688 Fixes#647:Added a History Override Extension
  History Override/history (1).png
  History Override/history.html
  History Override/history.png
  History Override/history16.png
  History Override/history32.png
  History Override/logic.js
  History Override/manifest.json
  History Override/style.css
Labels: gssoc, level2

#694 Added paint panel extension
  Paint Panel/index.html
  Paint Panel/manifest.json
  Paint Panel/script.js
  Paint Panel/style.css
Labels: gssoc, level2

#695 added connect four game extension
  Connect Four Game Extension/index.html
  Connect Four Game Extension/manifest.json
  Connect Four Game Extension/scripts/script.js
  Connect Four Game Extension/src/style.css
Labels: gssoc, level1

#696 Added Emoji Maker Extension
  Emoji Maker/index.html
  Emoji Maker/jquery.min.js
  Emoji Maker/manifest.json
  Emoji Maker/script.js
  Emoji Maker/style.css
Labels: gssoc, level2

#588 Aligned the box to the center of the page
  .DS_Store
  Tic-Tac-Toe Game/src/style.css
Labels: gssoc, level1

#687 Added Clash of tanks extension
  Clash Tanks/index.html
  Clash Tanks/manifest.json
  Clash Tanks/script.js
  Clash Tanks/style.css
Labels: gssoc, level2

#703 Styling in Age Calculator is added
  Age Calculator/index.html
Labels: gssoc, level1

#704 Adding analog clock
  Analog Clock/icons/images.jpeg
  Analog Clock/index.html
  Analog Clock/manifest.json
  Analog Clock/script.js
  Analog Clock/style20.css
Labels: gssoc, level1

#706 added battleship game extension
  Battleship Game Extension/index.html
  Battleship Game Extension/manifest.json
  Battleship Game Extension/scripts/script.js
  Battleship Game Extension/src/style.css
Labels: gssoc, level1

#707 Prayer Time Reminder Extension Added
  Prayer Time Reminder/background.png
  Prayer Time Reminder/bg.png
  Prayer Time Reminder/icon-128.png
  Prayer Time Reminder/icon-16.png
  Prayer Time Reminder/icon-48.png
  Prayer Time Reminder/manifest.json
  Prayer Time Reminder/notification.mp3
  Prayer Time Reminder/popup.css
  Prayer Time Reminder/popup.html
  Prayer Time Reminder/popup.js
Labels: gssoc, level2

#713 Added Treasure Hunt Game Extension
  Treasure Hunt/assets/cell-bg.png
  Treasure Hunt/assets/treasure.png
  Treasure Hunt/assets/wrong.png
  Treasure Hunt/manifest.json
  Treasure Hunt/popup.html
  Treasure Hunt/popup.js
  Treasure Hunt/styles.css
Labels: gssoc, level2

#720 added github daily activity checker extension
  GitHub Daily Activity Checker/background.js
  GitHub Daily Activity Checker/content.js
  GitHub Daily Activity Checker/images/icon128.png
  GitHub Daily Activity Checker/images/icon16.png
  GitHub Daily Activity Checker/images/icon48.png
  GitHub Daily Activity Checker/manifest.json
  GitHub Daily Activity Checker/popup.html
  GitHub Daily Activity Checker/popup.js
Labels: gssoc, level3

#721 Add Social Media Limiter Extension
  Social Media Limiter/background.js
  Social Media Limiter/icons/icon128.png
  Social Media Limiter/icons/icon16.png
  Social Media Limiter/icons/icon48.png
  Social Media Limiter/manifest.json
  Social Media Limiter/popup.css
  Social Media Limiter/popup.html
  Social Media Limiter/popup.js
Labels: gssoc, level1

#724 Added Tourism Website
  Tourism Website/css/responsive.css
  Tourism Website/css/style.css
  Tourism Website/img/GitHub120px.png
  Tourism Website/img/android-chrome-192x192.png
  Tourism Website/img/android-chrome-512x512.png
  Tourism Website/img/apple-touch-icon.png
  Tourism Website/img/bg.png
  Tourism Website/img/bg2.png
  Tourism Website/img/carousel-img1.jpg
  Tourism Website/img/carousel-img2.jpg
  Tourism Website/img/carousel-img3.jpg
  Tourism Website/img/carousel-img4.jpg
  Tourism Website/img/carousel-img5.jpg
  Tourism Website/img/carousel-img6.jpg
  Tourism Website/img/favicon-16x16.png
  Tourism Website/img/favicon-32x32.png
  Tourism Website/img/favicon.ico
  Tourism Website/img/header-bg.jfif
  Tourism Website/img/img1.jfif
  Tourism Website/img/img2.jfif
  Tourism Website/img/img3.png
  Tourism Website/img/img4.png
  Tourism Website/img/img5.png
  Tourism Website/img/img6.png
  Tourism Website/img/menu-btn.png
  Tourism Website/img/mountain.png
  Tourism Website/img/mountain_dark.jpg
  Tourism Website/index.html
  Tourism Website/js/script.js
  Tourism Website/manifest.json
Labels: gssoc, level2

#708 Image to PDF converter extension added
  Image To PDF/index.html
  Image To PDF/libs/jspdf.min.js
  Image To PDF/manifest.json
  Image To PDF/script.js
  Image To PDF/script2.js
  Image To PDF/styles.css
Labels: gssoc, level2

#735 Added Contact Manager App
  Contact Manager App/index.html
  Contact Manager App/manifest.json
  Contact Manager App/script.js
  Contact Manager App/style.css
Labels: gssoc, level1

#745 Fixes#717:Added Candy Crush Extension
  Candy Crush/background.jpg
  Candy Crush/candy.css
  Candy Crush/candy.js
  Candy Crush/images/Blue-Striped-Horizontal.png
  Candy Crush/images/Blue-Striped-Vertical.png
  Candy Crush/images/Blue-Wrapped.png
  Candy Crush/images/Blue.png
  Candy Crush/images/Choco.png
  Candy Crush/images/Green-Striped-Horizontal.png
  Candy Crush/images/Green-Striped-Vertical.png
  Candy Crush/images/Green-Wrapped.png
  Candy Crush/images/Green.png
  Candy Crush/images/Orange-Striped-Horizontal.png
  Candy Crush/images/Orange-Striped-Vertical.png
  Candy Crush/images/Orange-Wrapped.png
  Candy Crush/images/Orange.png
  Candy Crush/images/Purple-Striped-Horizontal.png
  Candy Crush/images/Purple-Striped-Vertical.png
  Candy Crush/images/Purple-Wrapped.png
  Candy Crush/images/Purple.png
  Candy Crush/images/Red-Striped-Horizontal.png
  Candy Crush/images/Red-Wrapped.png
  Candy Crush/images/Red.png
  Candy Crush/images/Yellow-Striped-Horizontal.png
  Candy Crush/images/Yellow-Striped-Vertical.png
  Candy Crush/images/Yellow-Wrapped.png
  Candy Crush/images/Yellow.png
  Candy Crush/images/blank.png
  Candy Crush/index.html
  Candy Crush/manifest.json
Labels: gssoc, level3

#747 PDF viewer/editor added
  PDF Viewer/index.html
  PDF Viewer/manifest.json
  PDF Viewer/script.js
  PDF Viewer/styles.css
Labels: gssoc, level1

#746 Fixes#718:Added a Doraemon Slide Puzzle
  Doraemon Slide Puzzle/1.jpg
  Doraemon Slide Puzzle/10.jpg
  Doraemon Slide Puzzle/2.jpg
  Doraemon Slide Puzzle/3.jpg
  Doraemon Slide Puzzle/4.jpg
  Doraemon Slide Puzzle/5.jpg
  Doraemon Slide Puzzle/6.jpg
  Doraemon Slide Puzzle/7.jpg
  Doraemon Slide Puzzle/8.jpg
  Doraemon Slide Puzzle/9.jpg
  Doraemon Slide Puzzle/index.html
  Doraemon Slide Puzzle/logo.png
  Doraemon Slide Puzzle/manifest.json
  Doraemon Slide Puzzle/puzzle.css
  Doraemon Slide Puzzle/puzzle.js
Labels: gssoc, level2

#755 added personal learning coach ext
  Personal Learning Coach/background.js
  Personal Learning Coach/icons/icon128.png
  Personal Learning Coach/icons/icon16.png
  Personal Learning Coach/icons/icon48.png
  Personal Learning Coach/manifest.json
  Personal Learning Coach/popup.html
  Personal Learning Coach/popup.js
Labels: gssoc, level2

#756 Added Turn on the light Game
  Turn on the Light Game/hammer.js
  Turn on the Light Game/index.html
  Turn on the Light Game/jquery.min.js
  Turn on the Light Game/manifest.json
  Turn on the Light Game/script.js
  Turn on the Light Game/style.css
Labels: gssoc, level3

#758 Added a preloader and Enhanced UI
  Fun Trivia Extension/popup.css
  Fun Trivia Extension/popup.html
  Fun Trivia Extension/popup.js
  Fun Trivia Extension/prelo.gif
Labels: gssoc, level2

#761 Calorie consumed calculator Added
  Calorie Consumed Calculator/assets/background.jpg
  Calorie Consumed Calculator/icon.png
  Calorie Consumed Calculator/manifest.json
  Calorie Consumed Calculator/popup.html
  Calorie Consumed Calculator/popup.js
  Calorie Consumed Calculator/style.css
Labels: gssoc, level1

#613 Image to text extension
  Image To Text/README.md
  Image To Text/images/arrow-right.png
  Image To Text/images/copy.png
  Image To Text/images/search.png
  Image To Text/images/upload.png
  Image To Text/indxe.html
  Image To Text/script.js
  Image To Text/style.css
Labels: gssoc, level1

#763 Styling in email validator is added.
  Email Validator/css/style.css
Labels: gssoc, level1

#768 The snake game extension added
  Snake game Extension/food.png
  Snake game Extension/game.js
  Snake game Extension/icon.png
  Snake game Extension/index.html
  Snake game Extension/manifest.json
  Snake game Extension/styles.css
Labels: gssoc, level2

#769 Add AquaSort: A Water Sorting Puzzle Game
  Aqua Sort/index.html
  Aqua Sort/manifest.json
  Aqua Sort/script.js
  Aqua Sort/style.css
Labels: gssoc, level2

#773 Song by word Extension added
  Song By Word Extension/manifest.json
  Song By Word Extension/popup.html
  Song By Word Extension/popup.js
  Song By Word Extension/script.js
  Song By Word Extension/styles.css
Labels: gssoc, level2

#777 added word count extension
  Word Count Extension/index.html
  Word Count Extension/manifest.json
  Word Count Extension/scripts/script.js
  Word Count Extension/src/styles.css
Labels: gssoc, level1

#779 Added Western-aim game Extension
  Western-aim-game Extension/img/ana-sayfa.png
  Western-aim-game Extension/img/bg.jpg
  Western-aim-game Extension/img/giris-mobile.jpg
  Western-aim-game Extension/img/giris.jpg
  Western-aim-game Extension/img/github.png
  Western-aim-game Extension/img/kolay.png
  Western-aim-game Extension/img/mobile.png
  Western-aim-game Extension/img/orta.png
  Western-aim-game Extension/img/target.png
  Western-aim-game Extension/img/zor.png
  Western-aim-game Extension/index.html
  Western-aim-game Extension/manifest.json
  Western-aim-game Extension/oyun-kolay.html
  Western-aim-game Extension/oyun-orta.html
  Western-aim-game Extension/oyun-zor.html
  Western-aim-game Extension/script.js
  Western-aim-game Extension/sound/click.mp3
  Western-aim-game Extension/sound/empty-click.mp3
  Western-aim-game Extension/sound/music.mp3
  Western-aim-game Extension/styles.css
Labels: gssoc, level2

#782 Add Decision Tree extension (fixes #678)
  Decision Tree/icon.png
  Decision Tree/index.html
  Decision Tree/manifest.json
  Decision Tree/script.js
  Decision Tree/style.css
Labels: gssoc, level2

#784 Code Comments remover added
  Code Comments Remover/manifest.json
  Code Comments Remover/popup.css
  Code Comments Remover/popup.html
  Code Comments Remover/popup.js
Labels: gssoc, level2

#800 Styling of puzzle game is enhanced.
  Puzzle Game Extension/popup.html
  Puzzle Game Extension/style.css
Labels: gssoc, level1

#793 The uno game extension is added
  UNO Game Extension/icon.png
  UNO Game Extension/icons/icon128.png
  UNO Game Extension/icons/icon16.png
  UNO Game Extension/icons/icon48.png
  UNO Game Extension/manifest.json
  UNO Game Extension/popup.html
  UNO Game Extension/script.js
  UNO Game Extension/style.css
Labels: gssoc, level3

#764 Added Degree-Radian Calculator: #757
  Degree Radian Calculator/Background-image/background_image.jpeg
  Degree Radian Calculator/README.md
  Degree Radian Calculator/index.html
  Degree Radian Calculator/manifest.json
  Degree Radian Calculator/script.js
  Degree Radian Calculator/style.css
Labels: gssoc, level2

#783 Added Bookmark Landing Page
  Bookmark Landing Page/design/desktop-active-states.jpg
  Bookmark Landing Page/design/desktop-design.jpg
  Bookmark Landing Page/design/desktop-preview.jpg
  Bookmark Landing Page/design/mobile-active-nav.jpg
  Bookmark Landing Page/design/mobile-active-states.jpg
  Bookmark Landing Page/design/mobile-design.jpg
  Bookmark Landing Page/design/tab-2-design.jpg
  Bookmark Landing Page/design/tab-3-design.jpg
  Bookmark Landing Page/images/bg-dots.svg
  Bookmark Landing Page/images/favicon-32x32.png
  Bookmark Landing Page/images/icon-arrow.svg
  Bookmark Landing Page/images/icon-close.svg
  Bookmark Landing Page/images/icon-error.svg
  Bookmark Landing Page/images/icon-facebook.svg
  Bookmark Landing Page/images/icon-hamburger.svg
  Bookmark Landing Page/images/icon-twitter.svg
  Bookmark Landing Page/images/illustration-features-tab-1.svg
  Bookmark Landing Page/images/illustration-features-tab-2.svg
  Bookmark Landing Page/images/illustration-features-tab-3.svg
  Bookmark Landing Page/images/illustration-hero.svg
  Bookmark Landing Page/images/logo-bookmark.svg
  Bookmark Landing Page/images/logo-chrome.svg
  Bookmark Landing Page/images/logo-firefox.svg
  Bookmark Landing Page/images/logo-opera.svg
  Bookmark Landing Page/index.html
  Bookmark Landing Page/manifest.json
  Bookmark Landing Page/styles.css
Labels: gssoc, level2

#803 Video compressor extension added
  Video Compressor Extension/manifest.json
  Video Compressor Extension/popup.html
  Video Compressor Extension/popup.js
  Video Compressor Extension/style.css
Labels: gssoc, level2

#805 Fidget Spinner Game
  Fidget spinner Game/icon.png
  Fidget spinner Game/manifest.json
  Fidget spinner Game/popup.html
  Fidget spinner Game/script.js
  Fidget spinner Game/style.css
Labels: gssoc, level2

#806 image gallary changes done
  Image Gallery/assets/pic1.jpg
  Image Gallery/assets/pic2.jpg
  Image Gallery/assets/pic3.jpg
  Image Gallery/assets/pic4.jpg
  Image Gallery/assets/pic5.jpg
  Image Gallery/index.html
  Image Gallery/main.js
  Image Gallery/manifest.json
  Image Gallery/style.css
Labels: gssoc, level2

#811 Added otHello-board-game extension
  Othello Board Game/index.html
  Othello Board Game/manifest.json
  Othello Board Game/scripts/board.js
  Othello Board Game/scripts/cell.js
  Othello Board Game/scripts/index.js
  Othello Board Game/static/othello-board-game-ss.jpg
Labels: gssoc, level2

#813 Adding world holiday Search ext wrt#702
  World Holiday Search Engine/index.html
  World Holiday Search Engine/manifest.json
  World Holiday Search Engine/script.js
  World Holiday Search Engine/styles.css
Labels: gssoc, level2

#817 Adding ai image generator wrt #710
  AI Image Generator/index.html
  AI Image Generator/manifest.json
  AI Image Generator/script.js
  AI Image Generator/style.css
Labels: gssoc, level2

#819 Add stick notes
  Sticky Notes/index.html
  Sticky Notes/logo.png
  Sticky Notes/script.js
  Sticky Notes/style.css
Labels: gssoc, level2

#824 Fixes #33
  Grammar Checker/game-28-128.png
  Grammar Checker/game-28-48.png
  Grammar Checker/index.html
  Grammar Checker/manifest.json
  Grammar Checker/scripts/script.js
  Grammar Checker/src/style.css
Labels: gssoc, level2

#825 Fixes #244
  Hangman Game/assets/hangman-0.svg
  Hangman Game/assets/hangman-1.svg
  Hangman Game/assets/hangman-2.svg
  Hangman Game/assets/hangman-3.svg
  Hangman Game/assets/hangman-4.svg
  Hangman Game/assets/hangman-5.svg
  Hangman Game/assets/hangman-6.svg
  Hangman Game/assets/lost.gif
  Hangman Game/assets/victory.gif
  Hangman Game/game-28-128.png
  Hangman Game/game-28-48.png
  Hangman Game/index.html
  Hangman Game/manifest.json
  Hangman Game/scripts/script.js
  Hangman Game/scripts/word-list.js
  Hangman Game/src/style.css
Labels: gssoc, level1

#826 Made changes in the Anime section and made it responsive too
  Anime Quote Extension/index.html
  Anime Quote Extension/script.js
Labels: gssoc, level1

#828 Enhance Music Player UI
  Music Extension/index.html
Labels: gssoc, level1

#837 Bug in Number Guessing game has been solved.
  Number Guess Game JS Extension/scripts/script.js
Labels: gssoc, level1

#838 Added Video to Audio Extension
  Video to Audio/index.html
  Video to Audio/manifest.json
  Video to Audio/script.js
  Video to Audio/styles.css
Labels: gssoc, level1

#843 Added a Doodle Jump Extension
  Doodle Jump/doodlejump.css
  Doodle Jump/doodlejump.js
  Doodle Jump/doodlejumpbg.png
  Doodle Jump/doodler-left.png
  Doodle Jump/doodler-right.png
  Doodle Jump/index.html
  Doodle Jump/manifest.json
  Doodle Jump/platform-broken.png
  Doodle Jump/platform.png
Labels: gssoc, level2

#847 Code Compiler added
  Code Compiler/README.md
  Code Compiler/background.js
  Code Compiler/manifest.json
  Code Compiler/popup.html
  Code Compiler/popup.js
  Code Compiler/server.js
Labels: gssoc, level2

#849 Added Movies Extension
  Movies/index.html
  Movies/manifest.json
  Movies/scripts/index.js
  Movies/scripts/services.js
  Movies/static/lovely-movies-ss.jpg
  Movies/styles/styles.css
Labels: gssoc, level2

#850 frontend and guide added to dictionery
  Dictionary Extension/manifest.json
  Dictionary Extension/popup.html
Labels: gssoc, level1

#851 Added Brick Breaker extension
  Brick Breaker/breakout.css
  Brick Breaker/breakout.js
  Brick Breaker/index.html
  Brick Breaker/manifest.json
Labels: gssoc, level2

#864 Pop My Balloon game extension added
  Pop My Balloon/BallonText.html
  Pop My Balloon/BalloonAnimation.css
  Pop My Balloon/index.html
  Pop My Balloon/script.js
  Pop My Balloon/styles.css
Labels: gssoc, level2

#858 Added Font Changer Extension
  Font Changer/README.md
  Font Changer/icons/extn_icon.png
  Font Changer/manifest.json
  Font Changer/override.js
  Font Changer/popup.html
  Font Changer/style.css
Labels: gssoc, level1

#873 Added Dino Runner Extension
  Dino Runner/dino.css
  Dino Runner/dino.js
  Dino Runner/img/big-cactus1.png
  Dino Runner/img/big-cactus2.png
  Dino Runner/img/big-cactus3.png
  Dino Runner/img/bird1.png
  Dino Runner/img/bird2.png
  Dino Runner/img/cactus1.png
  Dino Runner/img/cactus2.png
  Dino Runner/img/cactus3.png
  Dino Runner/img/cloud.png
  Dino Runner/img/dino-dead.png
  Dino Runner/img/dino-duck1.png
  Dino Runner/img/dino-duck2.png
  Dino Runner/img/dino-jump.png
  Dino Runner/img/dino-run1.png
  Dino Runner/img/dino-run2.png
  Dino Runner/img/dino.png
  Dino Runner/img/game-over.png
  Dino Runner/img/reset.png
  Dino Runner/img/track.png
  Dino Runner/index.html
  Dino Runner/manifest.json
Labels: gssoc, level2

#874 Daily delight Extension added
  Daily Delight Extension/manifest.json
  Daily Delight Extension/popup.html
  Daily Delight Extension/script.js
  Daily Delight Extension/style.css
  Video Compressor Extension/manifest.json
  Video Compressor Extension/popup.html
  Video Compressor Extension/popup.js
  Video Compressor Extension/style.css
Labels: gssoc, level2

#876 file saver added
  File Saver Extension/manifest.json
  File Saver Extension/popup.html
  File Saver Extension/popup.js
  File Saver Extension/styles.css
Labels: gssoc, level2

#878 Chnages height width of images
  Food Recipe/src/style.css
  Language_Translator/index.html
  Language_Translator/languages.js
  Language_Translator/manifest.json
  Language_Translator/script.js
  Language_Translator/style.css
  README.md
Labels: gssoc, level1

#879 Image Downloader added
  Image Downlaoder/manifest.json
  Image Downlaoder/popup.html
  Image Downlaoder/popup.js
  Image Downlaoder/styles.css
Labels: gssoc, level1

#882 Matrix Calculator
  Matrix Calculator/icon.png
  Matrix Calculator/manifest.json
  Matrix Calculator/popup.html
  Matrix Calculator/script.js
  Matrix Calculator/style.css
Labels: gssoc, level2

#883 Bug in background image in Maths Fact Extension is solved.
  Math Facts Extension/index.html
Labels: gssoc, level1

#884 Encryption and Security added to Password manager
  Password Manager/index.html
  Password Manager/scripts.js
  Password Manager/styles.css
Labels: gssoc, level1

#888 added code 365 problem extension
  code 365 problem of the day/manifest.json
  code 365 problem of the day/popup.html
  code 365 problem of the day/popup.js
  code 365 problem of the day/styles.css
  code 365 problem of the day/welcome.html
  code 365 problem of the day/welcome.js
Labels: gssoc, level3

#875 Added Company Portfolio Extension
  Company portfolio/about.html
  Company portfolio/contact.html
  Company portfolio/css/style.css
  Company portfolio/img/about-mission.jpg
  Company portfolio/img/about-objective.jpg
  Company portfolio/img/about-vision.jpg
  Company portfolio/img/about.jpg
  Company portfolio/img/banner.jpg
  Company portfolio/img/client-1.jpg
  Company portfolio/img/client-2.jpg
  Company portfolio/img/client-3.jpg
  Company portfolio/img/client-4.jpg
  Company portfolio/img/client-5.jpg
  Company portfolio/img/client-6.jpg
  Company portfolio/img/client-7.jpg
  Company portfolio/img/client-8.jpg
  Company portfolio/img/favicon.ico
  Company portfolio/img/portfolio-1.jpg
  Company portfolio/img/portfolio-2.jpg
  Company portfolio/img/portfolio-3.jpg
  Company portfolio/img/portfolio-4.jpg
  Company portfolio/img/portfolio-5.jpg
  Company portfolio/img/portfolio-6.jpg
  Company portfolio/img/slider-1.jpg
  Company portfolio/img/slider-2.jpg
  Company portfolio/img/slider-3.jpg
  Company portfolio/img/team-1.jpg
  Company portfolio/img/team-2.jpg
  Company portfolio/img/team-3.jpg
  Company portfolio/img/team-4.jpg
  Company portfolio/img/testimonial-1.jpg
  Company portfolio/img/testimonial-2.jpg
  Company portfolio/img/testimonial-3.jpg
  Company portfolio/index.html
  Company portfolio/js/main.js
  Company portfolio/manifest.json
  Company portfolio/portfolio.html
  Company portfolio/price.html
  Company portfolio/service.html
Labels: gssoc, level1

#877 Added Photography Portfolio Extension
  Photography Portfolio Extension/about.html
  Photography Portfolio Extension/assets/css/theme.css
  Photography Portfolio Extension/assets/img/blogs/img1.png
  Photography Portfolio Extension/assets/img/blogs/img2.png
  Photography Portfolio Extension/assets/img/blogs/img3.png
  Photography Portfolio Extension/assets/img/exhibitions/img01.png
  Photography Portfolio Extension/assets/img/exhibitions/img02.png
  Photography Portfolio Extension/assets/img/exhibitions/img03.png
  Photography Portfolio Extension/assets/img/exhibitions/img04.png
  Photography Portfolio Extension/assets/img/favicons/android-chrome-192x192.png
  Photography Portfolio Extension/assets/img/favicons/android-chrome-512x512.png
  Photography Portfolio Extension/assets/img/favicons/apple-touch-icon.png
  Photography Portfolio Extension/assets/img/favicons/browserconfig.xml
  Photography Portfolio Extension/assets/img/favicons/favicon-16x16.png
  Photography Portfolio Extension/assets/img/favicons/favicon-32x32.png
  Photography Portfolio Extension/assets/img/favicons/favicon.ico
  Photography Portfolio Extension/assets/img/favicons/manifest.json
  Photography Portfolio Extension/assets/img/favicons/site.webmanifest
  Photography Portfolio Extension/assets/img/gallery/1.png
  Photography Portfolio Extension/assets/img/gallery/2.png
  Photography Portfolio Extension/assets/img/gallery/3.png
  Photography Portfolio Extension/assets/img/gallery/4.png
  Photography Portfolio Extension/assets/img/gallery/5.png
  Photography Portfolio Extension/assets/img/gallery/6.png
  Photography Portfolio Extension/assets/img/gallery/7.png
  Photography Portfolio Extension/assets/img/gallery/8.png
  Photography Portfolio Extension/assets/img/gallery/9.png
  Photography Portfolio Extension/assets/img/home/img1.png
  Photography Portfolio Extension/assets/img/home/img2.png
  Photography Portfolio Extension/assets/img/home/img3.png
  Photography Portfolio Extension/assets/img/icons/dark-logo-icon.png
  Photography Portfolio Extension/assets/img/icons/logo-icon.png
  Photography Portfolio Extension/assets/img/icons/long-arrow.png
  Photography Portfolio Extension/assets/img/portfolio/img01.png
  Photography Portfolio Extension/assets/img/portfolio/img02.png
  Photography Portfolio Extension/assets/img/portfolio/img03.png
  Photography Portfolio Extension/assets/img/team/img1.png
  Photography Portfolio Extension/assets/img/team/img2.png
  Photography Portfolio Extension/assets/img/team/img3.png
  Photography Portfolio Extension/assets/img/team/img4.png
  Photography Portfolio Extension/assets/img/team/img5.png
  Photography Portfolio Extension/blog.html
  Photography Portfolio Extension/exhibitions.html
  Photography Portfolio Extension/gallery.html
  Photography Portfolio Extension/index.html
  Photography Portfolio Extension/manifest.json
  Photography Portfolio Extension/portfolio.html
Labels: gssoc, level1

#885 Stress management tip extension added
  Stress Management Tips/index.html
  Stress Management Tips/manifest.json
  Stress Management Tips/script.js
  Stress Management Tips/styles.css
Labels: gssoc, level2

#894 Added bar graph generator
  Bar Graph Generator/index.html
  Bar Graph Generator/manifest.json
  Bar Graph Generator/script.js
  Bar Graph Generator/style.css
Labels: gssoc, level2

#896 Enhnced the paint panel
  Paint Panel/index.html
  Paint Panel/manifest.json
  Paint Panel/script.js
  Paint Panel/scripts/material.min.js
  Paint Panel/scripts/pickr.es5.min.js
  Paint Panel/style.css
  Paint Panel/styles/material.indigo-pink.min.css
  Paint Panel/styles/nano.min.css
Labels: gssoc, level2

#898 Added Alien Buster Extension
  Alien Buster/alien-cyan.png
  Alien Buster/alien-magenta.png
  Alien Buster/alien-yellow.png
  Alien Buster/alien.png
  Alien Buster/index.html
  Alien Buster/manifest.json
  Alien Buster/ship.png
  Alien Buster/space.css
  Alien Buster/space.js
Labels: gssoc, level2

#895 Maze Game
  Maze Game/manifest.json
  Maze Game/maze.png
  Maze Game/popup.html
  Maze Game/script.js
  Maze Game/style.css
Labels: gssoc, level2

#900 Added Wapalyzer Extension
  Wapplyzer/css/styles.css
  Wapplyzer/html/background.html
  Wapplyzer/html/options.html
  Wapplyzer/html/popup.html
  Wapplyzer/images/icon_512.png
  Wapplyzer/images/wappalyzer.png
  Wapplyzer/js/background.js
  Wapplyzer/js/content.js
  Wapplyzer/js/dom.js
  Wapplyzer/js/popup.js
Labels: gssoc, level1

#901 Added Astronomical age calculator; Know your age in other worlds!
  Astronomical Age Calculator/assets/background.webp
  Astronomical Age Calculator/assets/favicon-128.jpg
  Astronomical Age Calculator/assets/favicon-16.jpg
  Astronomical Age Calculator/assets/favicon-48.jpg
  Astronomical Age Calculator/manifest.json
  Astronomical Age Calculator/popup.html
  Astronomical Age Calculator/script.js
  Astronomical Age Calculator/style.css
Labels: gssoc, level1

#923 Added Alarm Clock Extension
  Alarm Clock/files/clock.svg
  Alarm Clock/files/ringtone.mp3
  Alarm Clock/index.html
  Alarm Clock/manifest.json
  Alarm Clock/script.js
  Alarm Clock/style.css
Labels: gssoc, level1

#928 Fixes #397
  Direction Finder/game-28-128.png
  Direction Finder/game-28-48.png
  Direction Finder/index.html
  Direction Finder/manifest.json
  Direction Finder/scripts/script.js
  Direction Finder/scripts/sw.js
  Direction Finder/src/style.css
Labels: gssoc, level1

#932 Fixes #246
  Intellect Quest/game-28-128.png
  Intellect Quest/game-28-48.png
  Intellect Quest/index.html
  Intellect Quest/manifest.json
  Intellect Quest/scripts/script.js
  Intellect Quest/src/style.css
Labels: gssoc, level2

#936 In Aqua Sort Game, adjusting the bottom part of web page #853
  Aqua Sort/style.css
Labels: gssoc, level1

#960 Added Next button in Dad Jokes extension
  Dad Jokes/popup.css
  Dad Jokes/popup.html
  Dad Jokes/popup.js
Labels: gssoc, level1

#961 Keyboard Shortcut added
  Keyboard Shortcut/background.js
  Keyboard Shortcut/manifest.json
  Keyboard Shortcut/popup.css
  Keyboard Shortcut/popup.html
  Keyboard Shortcut/popup.js
Labels: gssoc, level2

#963 Added the bitwise calculator!
  Bitwise Calculator/assets/icon128.jpg
  Bitwise Calculator/assets/icon16.jpg
  Bitwise Calculator/assets/icon48.jpg
  Bitwise Calculator/manifest.json
  Bitwise Calculator/popup.html
  Bitwise Calculator/popup.js
  Bitwise Calculator/style.css
Labels: gssoc, level2

#909 favicon customizer added
  Favicon Customizer/background.js
  Favicon Customizer/manifest.json
  Favicon Customizer/popup.css
  Favicon Customizer/popup.html
  Favicon Customizer/popup.js
Labels: gssoc, level2

#968 tab suspender added
  Tab Suspender/background.js
  Tab Suspender/content.js
  Tab Suspender/manifest.json
  Tab Suspender/popup.css
  Tab Suspender/popup.html
  Tab Suspender/popup.js
Labels: gssoc, level1

#844 Added Image Compressor
  Image Compressor/README.md
  Image Compressor/index.html
  Image Compressor/main.js
  Image Compressor/style.css
Labels: gssoc, level2

#929 Added Simon Game Extension
  Simon Game/128.png
  Simon Game/16.png
  Simon Game/32.png
  Simon Game/btn Flash.mp3
  Simon Game/manifest.json
  Simon Game/popup.css
  Simon Game/popup.html
  Simon Game/popup.js
  Simon Game/prelo.gif
  Simon Game/wrong btn.mp3
Labels: gssoc, level2

#934 Etch-a-sketch drawer extension added
  Etch Sketch/index.html
  Etch Sketch/manifest.json
  Etch Sketch/script.js
  Etch Sketch/styles.css
Labels: gssoc, level2

#970 Added the Cubic Equation Solver Extension!
  Cubic Equation Solver Extension/assets/icon128.webp
  Cubic Equation Solver Extension/assets/icon16.webp
  Cubic Equation Solver Extension/assets/icon48.webp
  Cubic Equation Solver Extension/cubicSolver.js
  Cubic Equation Solver Extension/manifest.json
  Cubic Equation Solver Extension/popup.html
  Cubic Equation Solver Extension/popup.js
  Cubic Equation Solver Extension/style.css
Labels: gssoc, level2

#978 added resume ATS scanner extension
  Resume ATS Scanner/manifest.json
  Resume ATS Scanner/popup.html
  Resume ATS Scanner/popup.js
  Resume ATS Scanner/styles.css
  Resume ATS Scanner/welcome.html
  Resume ATS Scanner/welcome.js
Labels: gssoc, level3

#982 added AI photo editor extension
  AI Photo Editor/manifest.json
  AI Photo Editor/popup.html
  AI Photo Editor/popup.js
  AI Photo Editor/styles.css
  AI Photo Editor/welcome.html
  AI Photo Editor/welcome.js
Labels: gssoc, level2

#984 carbon footprint extension
  Carbon Foot Print Extension/background.avif
  Carbon Foot Print Extension/background.js
  Carbon Foot Print Extension/manifest.json
  Carbon Foot Print Extension/popup.css
  Carbon Foot Print Extension/popup.html
  Carbon Foot Print Extension/popup.js
  Workout Planner Extension/popup.css
Labels: gssoc, level2

#985 Body Fat Percentage Extension
  Body Fat Percentage Extension/background.js
  Body Fat Percentage Extension/bg.jpg
  Body Fat Percentage Extension/icon128.jpg
  Body Fat Percentage Extension/icon16.jpg
  Body Fat Percentage Extension/icon48.jpg
  Body Fat Percentage Extension/manifest.json
  Body Fat Percentage Extension/popup.css
  Body Fat Percentage Extension/popup.html
  Body Fat Percentage Extension/popup.js
Labels: gssoc, level1

#995 Added UBlock ad block
  UBlock/about.html
  UBlock/css/about.css
  UBlock/css/popup-fenix.css
  UBlock/css/settings.css
  UBlock/css/support.css
  UBlock/dashboard.html
  UBlock/js/about.js
  UBlock/js/background.js
  UBlock/js/settings.js
  UBlock/no-dash.html
  UBlock/popup-fenix.html
  UBlock/settings.html
  UBlock/support.html
Labels: gssoc, level2

#996 added discount tab in bill splitter
  Bill Splitter/index.html
  Bill Splitter/scripts/script.js
  Bill Splitter/src/style.css
Labels: gssoc, level1

#1003 css inspector added
  CSS Inspector/background.js
  CSS Inspector/content.js
  CSS Inspector/manifest.json
  CSS Inspector/popup.css
  CSS Inspector/popup.html
  CSS Inspector/popup.js
Labels: gssoc, level2

#1007 shopping cart saver
  Shopping Cart Saver/background.js
  Shopping Cart Saver/manifest.json
  Shopping Cart Saver/popup.css
  Shopping Cart Saver/popup.html
  Shopping Cart Saver/popup.js
Labels: gssoc, level2

#1011 Added Differential Calculator extension!!
  Differential Calculator Extension/icons/icon128.png
  Differential Calculator Extension/icons/icon16.png
  Differential Calculator Extension/icons/icon48.png
  Differential Calculator Extension/libs/math.min.js
  Differential Calculator Extension/manifest.json
  Differential Calculator Extension/popup.html
  Differential Calculator Extension/script.js
  Differential Calculator Extension/style.css
Labels: gssoc, level2

#1012 Added Eco Warrior Game Extension
  Eco Warrior/assets/litter.png
  Eco Warrior/assets/tree.png
  Eco Warrior/game.js
  Eco Warrior/manifest.json
  Eco Warrior/popup.html
  Eco Warrior/style.css
Labels: gssoc, level2

#1013 Updating UI of aqua sort game
  Aqua Sort/bg1.jpg
  Aqua Sort/index.html
  Aqua Sort/script.js
  Aqua Sort/style.css
Labels: gssoc, level1

#1016 Added definite integration Calculator extension
  Definite Integral Calculator Extension/images/icon128.png
  Definite Integral Calculator Extension/images/icon16.png
  Definite Integral Calculator Extension/images/icon48.png
  Definite Integral Calculator Extension/lib/math.min.js
  Definite Integral Calculator Extension/manifest.json
  Definite Integral Calculator Extension/popup.html
  Definite Integral Calculator Extension/script.js
  Definite Integral Calculator Extension/style.css
Labels: gssoc, level2

#1022 Added Admin Panel
  Admin Dashboard Panel/Images/logo.png
  Admin Dashboard Panel/Images/profile.jpg
  Admin Dashboard Panel/index.html
  Admin Dashboard Panel/manifest.json
  Admin Dashboard Panel/script.js
  Admin Dashboard Panel/style.css
Labels: gssoc, level2

#1026 Added Bubble Game
  Bubble Game/index.html
  Bubble Game/index.js
  Bubble Game/manifest.json
  Bubble Game/style.css
Labels: gssoc, level2

#1029 Added Newsletter Extension
  Newsletter/design/active-states.jpg
  Newsletter/design/desktop-design.jpg
  Newsletter/design/desktop-preview.jpg
  Newsletter/design/desktop-success-active.jpg
  Newsletter/design/desktop-success.jpg
  Newsletter/design/error-states.jpg
  Newsletter/design/mobile-design.jpg
  Newsletter/design/mobile-success.jpg
  Newsletter/images/favicon-32x32.png
  Newsletter/images/icon-list.svg
  Newsletter/images/icon-success.svg
  Newsletter/images/illustration-sign-up-desktop.svg
  Newsletter/images/illustration-sign-up-mobile.svg
  Newsletter/index.html
  Newsletter/manifest.json
  Newsletter/script.js
  Newsletter/style.css
Labels: gssoc, level2

#1031 Added Timely Extension
  Timely Clone/README.md
  Timely Clone/img ss/Screenshot (112).png
  Timely Clone/img ss/Screenshot (113).png
  Timely Clone/img ss/Screenshot (114).png
  Timely Clone/img ss/Screenshot (115).png
  Timely Clone/img ss/Screenshot (116).png
  Timely Clone/img ss/Screenshot (117).png
  Timely Clone/img ss/Screenshot (119).png
  Timely Clone/img ss/Screenshot (120).png
  Timely Clone/index.html
  Timely Clone/login.css
  Timely Clone/login.html
  Timely Clone/manifest.json
  Timely Clone/signup.css
  Timely Clone/signup.html
  Timely Clone/style.css
Labels: gssoc, level2

#1032 Fixed 2048 game
  2048 Game/css/number-box.css
  2048 Game/icon.png
  2048 Game/index.html
  2048 Game/js/jquery-3.2.1.js
  2048 Game/js/number-box.js
  2048 Game/number-box.html
  2048 Game/popup.css
  2048 Game/popup.html
  2048 Game/popup.js
Labels: gssoc, level1

#1034 Fixes #192
  3D Car Racing Game/1icon.png
  3D Car Racing Game/game-28-128.png
  3D Car Racing Game/game-28-48.png
  3D Car Racing Game/icon.png
  3D Car Racing Game/images/car04.png
  3D Car Racing Game/images/cloud.jpg
  3D Car Racing Game/images/finish.png
  3D Car Racing Game/images/hero.png
  3D Car Racing Game/images/tree.png
  3D Car Racing Game/index.html
  3D Car Racing Game/javascript/1.js
  3D Car Racing Game/javascript/null.js
  3D Car Racing Game/javascript/script.js
  3D Car Racing Game/manifest.json
  3D Car Racing Game/src/style.css
Labels: gssoc, level2

#1046 Added content setting extension
  Content Setting/manifest.json
  Content Setting/popup.css
  Content Setting/popup.html
  Content Setting/popup.js
Labels: gssoc, level2

#1051 Add extension for color matcher
  Color Matcher/background.js
  Color Matcher/content.js
  Color Matcher/manifest.json
  Color Matcher/popup.html
  Color Matcher/popup.js
  Color Matcher/styles.css
Labels: gssoc, level2

#1054 Fixes #822
  Complex CGPA Calculator/game-28-128.png
  Complex CGPA Calculator/game-28-48.png
  Complex CGPA Calculator/index.html
  Complex CGPA Calculator/manifest.json
  Complex CGPA Calculator/scripts/script.js
  Complex CGPA Calculator/src/bootstrap.min.css
  Complex CGPA Calculator/src/style.css
Labels: gssoc, level2

#1057 added tiny host extension
  Tiny Host/manifest.json
  Tiny Host/popup.html
  Tiny Host/popup.js
  Tiny Host/styles.css
  Tiny Host/welcome.html
  Tiny Host/welcome.js
Labels: gssoc, level1

#1058 Added AI pdf editor Extensiom
  AI Pdf Editor/manifest.json
  AI Pdf Editor/popup.html
  AI Pdf Editor/popup.js
  AI Pdf Editor/styles.css
  AI Pdf Editor/welcome.html
  AI Pdf Editor/welcome.js
Labels: gssoc, level3

#1060 Modifying placing locations of battleships in "battleship game"
  Battleship Game Extension/scripts/script.js
Labels: gssoc, level1

#1062 Linkedin helper
  Linkedin Helper/README.md
  Linkedin Helper/background.js
  Linkedin Helper/content.js
  Linkedin Helper/manifest.json
  Linkedin Helper/options.css
  Linkedin Helper/options.html
  Linkedin Helper/options.js
  Linkedin Helper/popup.css
  Linkedin Helper/popup.html
  Linkedin Helper/popup.js
Labels: gssoc, level3

#1064 world holiday fixed
  World Holiday Search Engine/manifest.json
Labels: gssoc, level1

#1066 added UI/UX designer extension
  AI UI/UX Designer/manifest.json
  AI UI/UX Designer/popup.html
  AI UI/UX Designer/popup.js
  AI UI/UX Designer/styles.css
  AI UI/UX Designer/welcome.html
  AI UI/UX Designer/welcome.js
Labels: gssoc, level2

#1067 Reset Button in Maths Fact Extension is added.
  Math Facts Extension/index.html
  Math Facts Extension/script.js
  Math Facts Extension/styles.css
Labels: gssoc, level1

#1068 Added Hackerrank Python Problems
  Hackerrank Python Problems/manifest.json
  Hackerrank Python Problems/popup.html
  Hackerrank Python Problems/popup.js
  Hackerrank Python Problems/styles.css
  Hackerrank Python Problems/welcome.html
  Hackerrank Python Problems/welcome.js
Labels: gssoc, level2

#1069 Added Reaction Time Tester Extension
  Reaction Time Tester/icons/icon16.png
  Reaction Time Tester/manifest.json
  Reaction Time Tester/popup.css
  Reaction Time Tester/popup.html
  Reaction Time Tester/popup.js
Labels: gssoc, level1

#1074 Added Time zone converter Extension
  Time Zone Converter Extension/icon/icon.png
  Time Zone Converter Extension/manifest.json
  Time Zone Converter Extension/popup.html
  Time Zone Converter Extension/script.js
  Time Zone Converter Extension/style.css
Labels: gssoc, level2

#1071 Anilist extension has been added
  Anilist/README.md
  Anilist/index.html
  Anilist/manifest.json
  Anilist/script.js
  Anilist/styles.css
Labels: gssoc, level2

#1075 Fixed chess game
  Chess Game/_css/styles.css
  Chess Game/assets/blacks/Black-Bishop.png
  Chess Game/assets/blacks/Black-King.png
  Chess Game/assets/blacks/Black-Knight.png
  Chess Game/assets/blacks/Black-Pawn.png
  Chess Game/assets/blacks/Black-Queen.png
  Chess Game/assets/blacks/Black-Rook.png
  Chess Game/assets/whites/White-Bishop.png
  Chess Game/assets/whites/White-King.png
  Chess Game/assets/whites/White-Knight.png
  Chess Game/assets/whites/White-Pawn.png
  Chess Game/assets/whites/White-Queen.png
  Chess Game/assets/whites/White-Rook.png
  Chess Game/game-28-128.png
  Chess Game/game-28-48.png
  Chess Game/index.html
  Chess Game/js/script.js
  Chess Game/manifest.json
  Chess Game/scripts/script.js
  Chess Game/src/style.css
Labels: gssoc, level1

#1085 Fixed the error of world clock extension
  World Clock Extension/index.html
  World Clock Extension/src/styles.css
Labels: gssoc, level1

#1086 About us for water sort
  Aqua Sort/aboutus.css
  Aqua Sort/aboutus.html
  Aqua Sort/index.html
  Aqua Sort/script.js
Labels: gssoc, level1

#1101 added c++ editor extension
  C++ Code Editor/manifest.json
  C++ Code Editor/popup.html
  C++ Code Editor/popup.js
  C++ Code Editor/styles.css
  C++ Code Editor/welcome.html
  C++ Code Editor/welcome.js
Labels: gssoc, level3

#1103 added figma extension
  Figma/manifest.json
  Figma/popup.html
  Figma/popup.js
  Figma/styles.css
  Figma/welcome.html
  Figma/welcome.js
Labels: gssoc, level2

#1104 Delete button for each player in Pictionary game is added.
  Pictionary Game/Index.html
  Pictionary Game/scripts/script.js
  Pictionary Game/src/styles.css
Labels: gssoc, level1

#1107 added spline extension
  Spline/manifest.json
  Spline/popup.html
  Spline/popup.js
  Spline/styles.css
  Spline/welcome.html
  Spline/welcome.js
Labels: gssoc, level2

#1108 Added the net salary calculator extension
  Net Salary Calculator Extension/icons/icon.png
  Net Salary Calculator Extension/manifest.json
  Net Salary Calculator Extension/popup.html
  Net Salary Calculator Extension/popup.js
  Net Salary Calculator Extension/style.css
Labels: gssoc, level2

#1165 added credit card payoff extension
  Credit Card Payoff/background.js
  Credit Card Payoff/bg.jpg
  Credit Card Payoff/manifest.json
  Credit Card Payoff/popup.css
  Credit Card Payoff/popup.html
  Credit Card Payoff/popup.js
Labels: gssoc, level2

#1164 added clothing size determiner
  Clothing Size Determiner/background.js
  Clothing Size Determiner/bg.jpg
  Clothing Size Determiner/domManager.js
  Clothing Size Determiner/manifest.json
  Clothing Size Determiner/popup.css
  Clothing Size Determiner/popup.html
  Clothing Size Determiner/popup.js
Labels: gssoc, level1

#1162 Added electricity bill extension
  Electricity Bill/background.js
  Electricity Bill/bg.jpg
  Electricity Bill/manifest.json
  Electricity Bill/popup.css
  Electricity Bill/popup.html
  Electricity Bill/popup.js
Labels: gssoc, level1

#1116 Interactive Periodic Table Extension added
  Interactive Periodic Table Extension/data.js
  Interactive Periodic Table Extension/index.html
  Interactive Periodic Table Extension/manifest.json
  Interactive Periodic Table Extension/script.js
  Interactive Periodic Table Extension/styles.css
Labels: gssoc, level2

#1112 added Java code editor extension
  Java Code Editor/manifest.json
  Java Code Editor/popup.html
  Java Code Editor/popup.js
  Java Code Editor/styles.css
  Java Code Editor/welcome.html
  Java Code Editor/welcome.js
Labels: gssoc, level3

#1113 Added a vector calculator extension which performs different operations
  Vector Calculator Extension/icons/icon.png
  Vector Calculator Extension/manifest.json
  Vector Calculator Extension/popup.html
  Vector Calculator Extension/popup.js
  Vector Calculator Extension/style.css
Labels: gssoc, level2

#1114 GitHub profile finder
  GitHub Profile Finder/index.html
  GitHub Profile Finder/manifest.json
  GitHub Profile Finder/scripts/script.js
  GitHub Profile Finder/src/style.css
Labels: gssoc, level2

#1117 Digital Detox Companion
  Digital Detox Companion/background.js
  Digital Detox Companion/icons/icon.png
  Digital Detox Companion/manifest.json
  Digital Detox Companion/popup.html
  Digital Detox Companion/popup.js
Labels: gssoc, level1

#1143 Added New Extension
  Python Code Editor/manifest.json
  Python Code Editor/popup.html
  Python Code Editor/popup.js
  Python Code Editor/styles.css
  Python Code Editor/welcome.html
  Python Code Editor/welcome.js
Labels: gssoc, level3

#1159 Added Factorial Calculator extension: #1063
  Factorial Calculator Extension/manifest.json
  Factorial Calculator Extension/popup.html
  Factorial Calculator Extension/script.js
  Factorial Calculator Extension/style.css
Labels: gssoc, level2

#1163 eye breaker reminder
  Eye Break Reminder/background.js
  Eye Break Reminder/manifest.json
  Eye Break Reminder/popup.html
  Eye Break Reminder/popup.js
  Eye Break Reminder/styles.css
Labels: gssoc, level1

#1183 removing negative values from input fields in BMI calculator
  BMI Calculator/popup.html
Labels: gssoc, level1
